tile-ai/tilelang

README.md, examples/dequantize_gemm/README.md, examples/dequantize_gemm/example_dequant_gemm_fine_grained.py, examples/quickstart.py, install_cpu.sh, install_cuda.sh, install_rocm.sh
This pull request includes several updates to the `README.md` file, improvements to example scripts, and modifications to installation scripts. The most important changes focus on improving documentation clarity and code consistency.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L27-R28): Removed redundant phrases and updated descriptions for better clarity. Added new information about ongoing additions of operators in the `examples` directory. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L27-R28) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L192-L193)
Code consistency improvements:
* …
=> [Doc] Fix installation scripts and docs for dequantize gemm

format.sh, src/transform/layout_inference.cc
CPU support introduced a flag `skip thread binding` into LayoutInference Pass, while it depends on buffer allocations to detect whether it's a cuda like device, which is not efficient and may introduce some bugs.
This pull request includes significant changes to the `format.sh` and `src/transform/layout_inference.cc` files, focusing on removing `clang-tidy` support and refactoring the layout inference logic. Below are the most important changes:
* [`format.sh`](diffhunk://#diff-ef87df35455e8abccb373a278caa1c24262425cff2cb2da5fff1d34775702ec2L257-L312): Removed the entire section related to `clang-tidy` checks, including the installation check, function definitions, and script logic for running `clang-tidy` on files.
* [`src/transform/layout_inference.cc`](diffhunk://#diff-199e49dddc4965b89 …
=> [Bugfix] Replace thread binding detector in LayoutInference Pass

examples/flash_attention/example_mha_inference.py, src/layout/layout.cc, tilelang/layout/fragment.py
This PR adds `example_mha_inference.py`, which implements FlashDecoding in the Multi-Head Attention mechanism to optimize inference performance.
[example_mha_inference.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-a26c0e01f21d55c551a7dbb534bd920492f7f9990b954986351667395e1c39ce): Added new example documentation.
[layout.cc](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-8e8b85e9396c3aaaf378020a15e4274510e97a4fb17c7c5ac7047596e1ca37c5): Removed unnecessary checks.
[fragment.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-1a1c90eabbffb081c48d243d1622e9e747513926a12693974cc0a5ea31a0c80b): Fixed Fragment initialization bugs when forward_index = None.
=> [Dev] Add FlashDecoding example

testing/python/autotune/test_tilelang_autotune.py, testing/python/jit/test_tilelang_jit_gemm.py, testing/python/transform/test_tilelang_transform_legalize_safe_memory_access.py, testing/python/transform/test_tilelang_transform_legalize_vectorized_loop.py
This pull request introduces several new test files and functions to enhance the testing capabilities for matrix multiplication and memory access transformations in the `tilelang` library. The most important changes include adding new test functions for autotuning matrix multiplication kernels, creating new test functions for JIT compilation of GEMM kernels, and adding tests for legalizing safe memory access and vectorized loops.
* [`testing/python/autotune/test_tilelang_autotune.py`](diffhunk://#diff-ed937bc9bbc7d4e868f4d7af2ebccdd6590d1675d2e9b57f315e56d57264adfeR1-R297): Added functions `ref_program`, `get_configs`, `matmul`, `test_autotune_get_configs`, and `test_autotune_matmul` to test autotuning of matrix multiplication kernels.
* …
=> [Dev] Implement test case for tilelang transformations

src/transform/vectorize_loop.cc, testing/python/transform/test_tilelang_transform_vectorize_loop.py, tilelang/engine/__init__.py, tilelang/engine/lower.py, tilelang/language/__init__.py, tilelang/language/parser/parser.py, tilelang/transform/__init__.py
This pull request includes several changes to the `tilelang` engine and language modules, focusing on importing additional functions, modifying transformation passes, and updating parser imports. The most important changes are listed below:
* [`tilelang/engine/__init__.py`](diffhunk://#diff-7c6f75bcdf3c9723e9e80d4d47ed18bbc7310ad464c9209aa22989b7b8658860L4-R4): Added `is_device_call` to the imports from `.lower`.
* [`tilelang/engine/lower.py`](diffhunk://#diff-e8395ac8f9a0848926b352900043a46a38d67a3c2762dc0f1267f5d296207a63L147): Moved the `VectorizeLoop` transformation pass to a later point in the `lower` function. [[1]](diffhunk://#diff-e8395ac8f9a0848926b352900043a46a38d67a3c2762dc0f1267f5d296207a63L147) [[2]](diffhunk://#diff-e8395ac8f9a0848926b352900043a46a38d67a3c2762dc0f1267f5d29620 …
=> [Dev] Separate `LoopVectorize` Pass from upstream tvm

.github/workflows/ci.yml, src/target/codegen_cuda.cc, src/target/codegen_cuda.h, src/tl_templates/cuda/common.h, src/tl_templates/cuda/cuda_fp8.h, src/transform/vectorize_loop.cc, testing/python/jit/test_tilelang_jit_callback.py, testing/python/jit/test_tilelang_jit_gemm.py, testing/python/kernel/test_tilelang_kernel_dequantize_gemm.py, testing/python/kernel/test_tilelang_kernel_fp8_gemm_mma.py, testing/python/kernel/test_tilelang_kernel_fp8_gemv_simt.py, testing/python/kernel/test_tilelang_kernel_gemm_mma_intrinsic.py, testing/python/kernel/test_tilelang_kernel_gemv_simt.py, testing/python/transform/test_tilelang_transform_vectorize_loop.py, tilelang/contrib/dlpack.py, tilelang/engine/__init__.py, tilelang/engine/lower.py, tilelang/intrinsics/utils.py, tilelang/jit/__init__.py, tilelang/jit/adapter/__init__.py, tilelang/jit/adapter/dlpack.py, tilelang/jit/kernel.py, tilelang/language/__init__.py, tilelang/language/parser/parser.py, tilelang/profiler/__init__.py, tilelang/transform/__init__.py, tilelang/transform/simplify.py, tilelang/utils/tensor.py
This pull request includes several changes to enhance the CUDA code generation and improve the overall functionality of the TileLang engine. The most important changes include the addition of support for FP8 types, the introduction of a global barrier synchronization mechanism, and updates to various data type handling and vectorization processes.
* Added support for FP8 types, including the `GetFP8Type` function and necessary includes in the `Finish` method. (`src/target/codegen_cuda.cc`, `src/tl_templates/cuda/cuda_fp8.h`) [[1]](diffhunk://#diff-c3ab436cd4bc043109e6e9bcc9d813a4bc89311efd35f19203970bf10f7596d6R26-R53) [[2]](diffhunk://#diff-c3ab436cd4bc043109e6e9bcc9d813a4bc89311efd35f19203970bf10f7596d6R109-R129) [[3]](diffhunk://#diff-4e56e8e78cc0b762cf12de8b7eef9c43b9708e23e1beece1e1f7 …
=> [Dev] Support FP8 Codegen for cuda backend

testing/python/kernel/test_tilelang_kernel_flash_linear_attention.py, testing/python/kernel/test_tilelang_kernel_mha.py, testing/python/transform/test_tilelang_transform_multi_version_buffer.py, testing/python/transform/test_tilelang_transform_warp_specialized.py, tilelang/language/builtin.py
[test_tilelang_kernel_flash_linear_attention.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-82846bdea189aafa26e75f686fe79d0ab09d88018747d323aef6a4f38514d1c4) and [test_tilelang_kernel_mha.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-079ce371b2467bf602a868aa5a543077307133f0ac0b82d4e892f29a26c5fe2c): Relaxed the mismatch ratio restrictions in the flash_linear_attention and mha tests.
[test_tilelang_transform_multi_version_buffer.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-25de53a6b60246fd9111b5ca1aa4330ef77b264cb63c2b92c4266eb0c182a37d): Added test cases for tilelang transform MultiVersionBuffer.
[test_tilelang_transform_warp_specialized.py](https://github.com/tile-ai/tilela …
=> [CI][Test] Add test cases for tilelang transform MultiVersionBuffer and WarpSpecialized

examples/gemm/README.md, testing/python/jit/test_tilelang_jit_gemm_ctypes.py, testing/python/kernel/test_tilelang_kernel_int4_gemm_mma.py, tilelang/jit/adapter/ctypes/adapter.py, tilelang/jit/adapter/ctypes/wrapper.py, tilelang/language/__init__.py, tilelang/profiler/__init__.py, tilelang/utils/language.py
This pull request introduces several changes to the `tilelang` project, focusing on improving the `ctypes` adapter and adding new benchmarking and testing functionalities. The most important changes include adding new test functions, modifying the `CtypesKernelAdapter` class to handle dynamic symbolic shapes, and updating the `tilelang.language` module to support symbolic variables.
* Added new test functions `test_ctypes_kernel_do_bench`, `test_ctypes_kernel_multi_stream`, and `test_ctypes_dynamic_shape` to evaluate the performance and correctness of the `ctypes` kernel under different conditions.
* Updated the `CtypesKernelAdapter` class to handle dynamic symbolic shapes by introducing a `dynamic_symbolic_map` and the `_process_dynamic_symbolic` method.
* Added properties `prim_func`, …
=> [Feature] Add CTypes JIT kernel support

docker/Dockerfile.cu118, docker/Dockerfile.cu121, docker/Dockerfile.cu123, docker/Dockerfile.cu124, docker/Dockerfile.cu125, docker/Dockerfile.cu126, docker/README.md
Create Dockerfiles for CUDA versions 11.8, 12.1, 12.3, 12.4, and 12.5, using the latest PyTorch NGC base images. Update docker/README.md to provide clearer instructions for building and running the Docker container with a specific CUDA version.
=> [Docker] Add Dockerfiles for multiple CUDA versions

MANIFEST.in, format.sh, maint/scripts/build_docs.sh, maint/scripts/docker_local_distribute.sh, maint/scripts/docker_pypi_distribute.sh, maint/scripts/local_distribution_tox.sh, maint/scripts/pypi_distribution_tox.sh, requirements-build.txt, requirements-dev.txt, requirements-lint.txt, requirements-test.txt, setup.py
This pull request includes several changes to improve the organization and functionality of the build and linting scripts, as well as some licensing updates. The most important changes include moving linting requirements to a separate file, adding new scripts for Docker-based distribution, and removing unnecessary code from `setup.py`.
* `maint/scripts/build_docs.sh`: Added copyright and licensing information. (F1de9305L1)
* [`maint/scripts/docker_local_distribute.sh`](diffhunk://#diff-15110692f1414c07d8e9a1db498e3fce45a1435aa6553154ea9816165580afe9R1-R21): Added new script for local Docker-based distribution with necessary environment setup and commands.
* [`maint/scripts/docker_pypi_distribute.sh`](diffhunk://#diff-61d1811c43ee3a7a99754d36cbd32699d7f7a7f27e9f4da98fa023cd2c3e05b4R1-R21): …
=> [Wheel] Provide a bare docker scripts to help build wheels for manylinux

examples/deepseek_mla/example_mla_decode.py, examples/gemm_splitk/example_tilelang_gemm_splitk.py, examples/gemm_streamk/example_tilelang_gemm_streamk.py
This pull request includes significant additions to three example files in the `examples` directory. These changes introduce new implementations of matrix multiplication and attention mechanisms using the `tilelang` library. The most important changes include the addition of new functions and classes to handle these operations, as well as the integration of `torch` for tensor operations and testing.
* Introduced the `flashattn` function for implementing the FlashAttention mechanism, including buffer allocations and kernel definitions.
* Added reference implementations (`ref_program`, `flash_split_ref`, and `reduce_ref`) for comparison and validation against the `tilelang` implementation.
* Included a main script to benchmark the `flashattn` implementation against the reference.
* Added …
=> [Example] Add Split-K and Stream-K Examples and move MLA from fld to mla

tilelang/engine/lower.py
This PR fixes the pass order in [lower.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-e8395ac8f9a0848926b352900043a46a38d67a3c2762dc0f1267f5d296207a63). The previous pass order caused host functions on Hopper to not be filtered to the host side.
=> [Bugfix] Bugfix of pass order for hopper

examples/flash_decoding/example_mla_decode.py
This pull request includes significant updates to the `flashattn` function in the `examples/flash_decoding/example_mla_decode.py` file. The changes primarily focus on improving the performance and accuracy of the function by modifying buffer shapes, adding new buffers, and updating the computation logic.
* Updated the buffer shapes for `Q`, `Q_pe`, `KV`, and `K_pe` to better align with the dimensions used in the computations.
* Added new shared buffers `Q_pe_shared`, `KV_shared`, and `K_pe_shared` to handle positional encoding and key-value pairs more efficiently.
* Replaced the use of `V_shared` with `KV_shared` in the GEMM operations to streamline the computation of attention outputs.
* Updated the `combine` macro to reflect the new buffer shapes, ensuring correct aggregation of partial …
=> [Dev] Update MLA decode kernel

examples/flash_attention/example_mha_fwd_varlen.py, tilelang/__init__.py, tilelang/engine/lower.py, tilelang/jit/adapter/cython/adapter.py, tilelang/jit/adapter/cython/cython_wrapper.pyx, tilelang/jit/adapter/wrapper.py, tilelang/utils/tensor.py
This pull request includes several changes to improve code clarity, fix bugs, and enhance logging across multiple files. The most important changes include removing unused imports, modifying function parameters, updating logging levels, and adding error handling for dynamic symbolic shapes.
Improvements to code clarity and functionality:
* [`examples/flash_attention/example_mha_fwd_varlen.py`](diffhunk://#diff-a2e3695585a1ea98bb68d1579d4cc8901ecbb0276366cecf0e5f536be497c03cL6): Removed unused import `tilelang.autotuner`, modified `flashattn` function to remove `max_seqlen_q` parameter, and added it to the `main` function instead. Cleaned up commented-out code and added print statements for better debugging. [[1]](diffhunk://#diff-a2e3695585a1ea98bb68d1579d4cc8901ecbb0276366cecf0e5f536be497 …
=> [Refactor] Set default log level from waning into info

examples/deepseek_mla/example_mla_decode.py, src/op/reduce.cc, src/tl_templates/cuda/reduce.h
- Remove redundant `acc_s_0` fragment in flash attention kernel
- Simplify memory copy and reduction operations
- Reorder memory copy and scaling steps for improved performance
- Add Hopper-specific synchronization method in CUDA reduce template
- Update reduce operation to use architecture-specific synchronization
=> [Dev] Adjust computation logic to avoid precision loss when casting acc_s from float to float16

benchmark/benchmark_matmul.py, tilelang/carver/roller/policy/default.py, tilelang/carver/utils.py
…Roller Hints Generation
- Replace BitBLAS imports with TileLang Carver imports in benchmark_matmul.py
- Modify roller hints generation using new TileLang Carver template and utility functions
- Update get_roller_hints_from_func to handle None cases and improve return logic
- Adjust DefaultPolicy to handle different codegen dictionary formats
=> [Refactor] Adapt Caver to benchmark

benchmark/benchmark_matmul.py, testing/python/autotune/test_tilelang_autotune.py
Following https://github.com/tile-ai/tilelang/pull/148, we can remove the unnecessary import check in `benchmark_matmul.py` so the user can run the code without install BitBLAS.
Also, https://github.com/tile-ai/tilelang/pull/148, forgets to change `test_tilelang_autotune.py`. This PR fixes it.
=> [Refactor] Remove BitBLAS Import Check in Benchmark

benchmark/matmul/benchmark_matmul.py, benchmark/matmul/benchmark_matmul_intrinsic.py, tilelang/carver/utils.py, tilelang/intrinsics/mma_macro_generator.py, tilelang/language/copy.py, tilelang/language/gemm.py, tilelang/primitives/gemm/base.py
This pull request includes several significant changes to the `benchmark/matmul` module, as well as updates to the `tilelang` library. The changes include renaming and refactoring files, modifying configuration parameters, and enhancing matrix multiplication functionality with new policies and optimizations.
* **File Renaming and Licensing:**
- Renamed `benchmark/benchmark_matmul.py` to `benchmark/matmul/benchmark_matmul.py` and added licensing information.
* **Configuration Adjustments:**
- Reduced the `topk` value from 20 to 10 in the `get_configs` function.
- Added new configuration parameters such as `policy` and updated existing ones like `thread_num` and `num_stages`. [[1]](diffhunk://#diff-f6569b098c377678a1b3e4ce25ca3245ba53e3d91f4a98a48d38b6818b4e5b51R80-R87) …
=> [Carver] Enhance Carver Adaptation for MatMul Benchmarking

docker/Dockerfile.cu118, docker/Dockerfile.cu120, docker/Dockerfile.cu121, docker/Dockerfile.cu123, docker/Dockerfile.cu124, docker/Dockerfile.cu125, docker/Dockerfile.cu126
Update Dockerfiles for CUDA 118, 120, 121, 123, 124, 125, and 126 to install libstdcxx-ng-12 from conda-forge, ensuring consistent standard library support across different CUDA versions
=> [Docker] Add libstdcxx-ng-12 to Dockerfiles for CUDA versions

src/tl_templates/cpp/common.h, src/tl_templates/cpp/gemm.h, src/tl_templates/cpp/half.hpp, src/tl_templates/cpu/common.h, src/tl_templates/cpu/gemm.h, testing/python/cpu/test_tilelang_cpu_gemm.py, tilelang/jit/adapter/libgen.py, tilelang/jit/adapter/utils.py, tilelang/jit/adapter/wrapper.py
A simple JIT compilation for a CPU has been implemented, with ctypes as the backend. It successfully passes the matmul operator's compile test using the command:
**tilelang.compile(cpu_func, -1, execution_backend="ctypes", target="c")**
=> Add cpu jit with backend ctypes

benchmark/matmul/benchmark_matmul.py, tilelang/autotuner/__init__.py
Prior to this PR, the auto tuning process of TileLang usually takes a long time especially for operators like GEMM (which requires a large search space). For each config, the tuning process is: (1). Compilation (on CPU); (2). Benchmarking (on GPU). We observe that (1) dominates the total time and can be parallelized using multi-threads or multi-process compilation.
In this PR, we use multi-threads to parallelize compilation because multi-process requires pickling TVM/ctypes objects, which raises some engineering problems.
Results in `benchmark_matmul.py` (Tested on `Intel(R) Xeon(R) Platinum 8378A CPU @ 3.00GHz, 128 threads`):
- w/o roller:  `Previous: ~30min   Now: 1~2min`
- w/ roller (topk=10): `Previous: 1~2min   Now: 20sec`
=> [Carver] Multi-Threads Compilation for Fast Auto Tuning

examples/deepseek_mla/example_mla_decode_paged.py
Simplify the control flow in the MLA decode kernel by replacing TileLang's T.If construct with a standard Python if statement. This change improves code readability and maintains the existing logic for handling sequence length constraints during block-wise computation.
=> [Refactor] Replace T.If with native Python if statement for mla paged kernel

tilelang/autotuner/__init__.py, tilelang/carver/matmul_analysis.py, tilelang/carver/roller/policy/tensorcore.py
This pull request includes several changes to improve logging, enhance error handling, and support new hardware architectures. The most important changes include adding a logger, updating the parallel compilation process, and extending support for newer CUDA architectures.
* [`tilelang/autotuner/__init__.py`](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7dd38R17-R18): Added a logger and improved error handling in the `target_fn` function. This includes logging compilation failures and timeouts with debug-level messages. [[1]](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7dd38R17-R18) [[2]](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7dd38L131-R181)
* …
=> [AutoTune] Enable config-performance trace

src/op/builtin.cc, src/op/builtin.h, src/op/bulk_copy.cc, src/op/op.h, src/transform/lower_tile_op.cc, tilelang/jit/__init__.py, tilelang/jit/adapter/ctypes/adapter.py, tilelang/jit/adapter/cython/adapter.py, tilelang/jit/adapter/wrapper.py, tilelang/jit/kernel.py
This commit introduces a new configuration option to disable TMA (Tensor Memory Access) lowering and updates copyright notices across multiple files. Key changes include:
- Add `kDisableTMALower` configuration option in builtin.h and builtin.cc
- Update copyright notices from Microsoft Corporation to Tile-AI Corporation
- Modify `LowerArgs` struct to include `disable_tma_lower` flag
- Update JIT compilation interfaces to support pass configuration
- Enhance error reporting in bulk copy lowering
- Propagate pass configuration through various adapter layers
=> [Feat] Append Pass Context and TMA lowering configuration option

src/transform/layout_inference.cc
- Update layout inference to handle thread variables more robustly
- Add explicit size check between infer_list_ and thread_var_vec_
- Modify thread variable access to use per-iteration thread variable
- Simplify thread predicate retrieval logic
- Add minor code cleanup and return variable assignment
Code to reproduce this bug:
```python
import tilelang
import tilelang.language as T
def test(
batch_size: int,
head_dim: int,
):
dtype = "float16"
@T.macro
def kernel1(
A: T.Buffer([batch_size, head_dim], dtype),
):
with T.Kernel(
batch_size, threads=128
) as by:
cur_batch = by
for j in T.Parallel(head_dim):
A[cur_batch, j] = 0.0
@T.macro
def kernel2(
B: T.Buffer([batch_size, head_dim], dtype),
):
with T.Kernel(
batch_size, threads=128
) as by:
cur_batch = by
for j in T.Parallel(head_dim): …
```
=> [Bugfix] Improve Thread Variable Handling in Layout Inference

setup.py
- Modify build_csrc function to use 90% of available CPU cores
- Ensure at least one job is used during compilation
- Improve build performance by dynamically adjusting parallel job count
=> [Enhancement] Optimize CMake build process with dynamic job count calculation

setup.py, testing/python/jit/test_tilelang_jit_gemm_cython.py, tilelang/jit/adapter/cython/cython_wrapper.pyx
This pull request introduces new functionality for handling dynamic shapes in Cython kernels and includes changes to both the test suite and the Cython wrapper implementation. The most important changes are summarized below:
* [`testing/python/jit/test_tilelang_jit_gemm_cython.py`](diffhunk://#diff-9b73e1ab167c1a34e01a085b75e3b49b447a0d8f373293d3e6a12248cf8dc328R410-R466): Added the `run_cython_dynamic_shape_with_out_idx` function to test dynamic shapes with Cython kernels and a corresponding test case `test_cython_dynamic_shape_with_out_idx`.
* [`tilelang/jit/adapter/cython/cython_wrapper.pyx`](diffhunk://#diff-8101f033a370463f49a5f1a4fbdd6a1deb01bf215ffc15fa44cb751e2f4c043dR10): Imported `tir` from `tvm` to handle dynamic shapes.
* …
=> [Bugfix] Add dynamic shape support with out_idx in Cython JIT kernel compilation

examples/norm/rms_norm.py, src/tl_templates/cuda/reduce.h
- Implement two RMS normalization implementations in TileLang:
* `rms_norm_splitk`: Split-K reduction approach for large matrices
* `rms_norm`: Full reduction kernel with simplified implementation
- Add reference implementation using PyTorch for validation
- Include performance benchmarking for both kernel variants
- Demonstrate flexible block size and matrix size configurations
=> [Dev][Bugfix] Add RMS Normalization Kernels and Fix Reduce Bug

src/transform/warp_specialized_rewriter.cc, testing/python/transform/test_tilelang_transform_lower_hopper_intrin.py
- Introduce `SetMaxNRegCollector` to collect register hints from SetMaxNReg calls
- Modify `WarpSpecializedRewriter` to use collected register hints for producer and consumer code
- Add validation checks for register hint values in the collector
- Remove SetMaxNReg calls during code transformation
- Enhance flexibility of register allocation in warp specialized rewriting
=> [Refactor] Add SetMaxNRegCollector to Improve Register Hint Handling in Warp Specialized Rewriter

src/op/builtin.cc, src/op/builtin.h, src/target/codegen_cuda.cc, src/tl_templates/cuda/copy_sm90.h, src/transform/inject_fence_proxy.cc, testing/python/transform/test_tilelang_transform_lower_hopper_intrin.py, tilelang/language/builtin.py
- Introduce TMAStoreArrive and TMAStoreWait operations for CUDA TMA store synchronization
- Add new builtin operations in op/builtin.cc and op/builtin.h
- Implement TMAStoreSyncInjector to automatically inject TMA store synchronization calls
- Update CUDA codegen to support new TMA store synchronization intrinsics
- Add Python language bindings for new TMA store synchronization operations
=> [Feature] Add TMA Store Synchronization Support

src/op/bulk_copy.cc, src/op/gemm.cc, src/op/gemm.h, src/target/codegen_cuda.cc, src/tl_templates/cuda/gemm_sm90.h, src/transform/layout_inference.cc
This pull request includes significant changes to the `Gemm` and `BulkCopy` operations, primarily aimed at improving performance and flexibility for different GPU architectures. Key changes include the introduction of new layout and swizzle patterns, conditional logic for enabling specific optimizations, and the addition of new headers and namespaces.
Improvements to `Gemm` operation:
* [`src/op/gemm.cc`](diffhunk://#diff-5cbeefe6d2ab80fbd44350603133779b381d613ca2f5b4f4a6bf89dbe98b6d2cL55-R62): Added conditional logic to enable Warp Group MMA (WGMMA) for Hopper targets and adjusted the `ComputeWarpPartition` method to consider the new `maybe_hopper_wgmma` parameter. [[1]](diffhunk://#diff-5cbeefe6d2ab80fbd44350603133779b381d613ca2f5b4f4a6bf89dbe98b6d2cL55-R62) …
=> [Enhancement] Allow mma fallback when wgmma is not supported

src/transform/if_stmt_binding.cc, src/transform/merge_if_stmt.cc, src/transform/warp_specialized_rewriter.cc, tilelang/engine/phase.py, tilelang/transform/__init__.py
- Add IfStmtBinding to bind If statements to each statement in SeqStmt, enhancing the handling of conditional statements.
- Introduce MergeIfStmt to merge consecutive If statements within SeqStmt, optimizing the structure of conditional logic.
- Update phase.py to apply IfStmtBinding and MergeIfStmt transformations for the "sm_90" target.
- Enhance __init__.py with new functions for IfStmtBinding and MergeIfStmt, providing a clear interface for these transformations.
=> [Dev] Implement IfStmtBinding and MergeIfStmt transformations

testing/python/language/test_tilelang_language_clamp.py, testing/python/language/test_tilelang_language_reshape.py, testing/python/language/test_tilelang_language_view.py, tilelang/jit/adapter/wrapper.py, tilelang/language/__init__.py, tilelang/language/customize.py
- Introduced new test files for reshape and view operations in the tilelang language.
- Implemented reshape and view functions in the customize module, enhancing buffer manipulation capabilities.
- Updated the language initialization to include the new functionalities.
- Removed unnecessary import from test_tilelang_language_clamp.py for cleaner code.
=> [Language] Introduce `T.reshape` and `T.view`

src/layout/gemm_layouts.cc, src/layout/layout.cc, src/layout/layout.h, src/op/gemm.cc, src/tl_templates/cuda/gemm_sm90.h, testing/python/issue/test_tilelang_issue_101.py
This pull request fixes issue #101.
The issue comes from the mismatch between the smem layout and the mma atom layout in this example.
Since the user specifies `GemmWarpPolicy.FullCol`, `num_warp_n` now equals 2 because of the 2 warp groups in total (256 threads).
This results in the selected mma atom being `wgmma.mma_async.m64n96k16`. However, the selection of the shared memory layout is not aware of `num_warp_n`, producing a 128B (64 x fp16) swizzle mode. As 64 cannot be divided by 96 from the mma atom, the issue occurs.
To fix this, we should also select the shared memory's layout with regard to the warp policy (see comment below).
We also need to adjust the code of layout inference correspondingly. We add a `continuity` parameter in `makeGemmABLayout` because now the matrix shape …
=> [Bugfix] Fix mismatch of shared memory layout and mma atom on Hopper

examples/deepseek_deepgemm/example_deepgemm_fp8_2xAcc.py, examples/gemm_fp8/example_tilelang_gemm_fp8_2xAcc.py
1. Implemented the fp8 gemm with T.gemm and add 2xAcc support for Hopper.
2. Implemented the deepgemm.
=> [Examples] Add fp8 gemm 2xAcc and deepgemm example

src/tl_templates/cuda/common.h, src/tl_templates/cuda/ldsm.h, src/transform/layout_inference.cc, tilelang/engine/param.py, tilelang/engine/phase.py, tilelang/jit/kernel.py, tilelang/utils/tensor.py
This pull request includes several changes to improve the CUDA codebase and update the logging mechanism. The most important changes include adding a new macro definition, updating function attributes to use the new macro, changing the logging mechanism for buffer checks, and updating licensing information.
Improvements to CUDA codebase:
* [`src/tl_templates/cuda/common.h`](diffhunk://#diff-a9affb584850fb57935aeb0a8450d96497f4534022304d408cb369a47d1e8130R27): Added a new macro definition `TL_DEVICE_NOINLINE` to specify noinline device functions.
* [`src/tl_templates/cuda/ldsm.h`](diffhunk://#diff-62f8dd53fd99d691f74a1dba673a393154130ad3cc3f7e7e0d8b3dbbc6b96ec2L9-R9): Updated multiple functions to use `TL_DEVICE_NOINLINE` instead of `TL_DEVICE` to prevent inlining of these functions. …
=> [Bugfix] Disable force inline for ldmatrix

tilelang/jit/adapter/wrapper.py
This pull request includes several changes to the `tilelang/jit/adapter/wrapper.py` file to improve the handling of TMA descriptor arguments and simplify the codebase. The most important changes are:
Improvements to TMA descriptor argument handling:
* Modified `func_call_args` to accept an optional `desc_name_map` parameter and updated its logic to handle descriptor names more flexibly (`tilelang/jit/adapter/wrapper.py`, [tilelang/jit/adapter/wrapper.pyL133-R141](diffhunk://#diff-11632097304818e018a5c33430f70f6e9c98af09b886c20cca8dc41051633298L133-R141)).
* Updated the `legalize_c` function to initialize and use `desc_name_map` for generating TMA descriptor arguments (`tilelang/jit/adapter/wrapper.py`, [[1]](diffhunk://#diff-11632097304818e018a5c33430f70f6e9c98af09b886c20cca8dc41051633298L …
=> [Bugfix] Support duplicate tma desc declaration

testing/python/language/test_tilelang_language_clamp.py
- Renamed `clamp` to `clamp_within_bounds` and `clamp_v2` to `clamp_value_range` for improved clarity.
- Updated dtype handling in `clamp_value_range` to use the correct tensor dtype.
- Modified test cases to reflect the new function names and ensure proper dtype conversion using `map_torch_type`.
- Enhanced the reference program for clamping to utilize the updated tensor dtype, improving accuracy in tests.
=> [Refactor] Rename clamp functions and enhance dtype handling in tests

tilelang/jit/adapter/base.py, tilelang/jit/adapter/ctypes/adapter.py, tilelang/jit/adapter/cython/adapter.py, tilelang/jit/kernel.py
- Updated CtypesKernelAdapter and CythonKernelAdapter to include kernel_global_source for improved source code retrieval.
- Modified the _legalize_result_idx method in BaseKernelAdapter to accept Optional[List[int]] for better flexibility.
- Added comments to clarify the purpose of kernel_global_source in both adapters, enhancing code readability and maintainability.
=> [Enhancement] Simplify kernel source extraction in JIT adapters

testing/python/language/test_tilelang_language_reduce_max.py
* Introduced a new test file for the reduce_max operation in the tilelang language module.
* Implemented the reduce_max functionality using T.prim_func, including local memory allocation and result copying.
* Added tests for various input sizes and data types to ensure correctness of the reduce_max implementation.
* Enhanced profiling assertions to validate the output against reference implementations.
=> [Feature] Add reduce_max corresponding tests

src/transform/warp_specialized_rewriter.cc
This pull request includes a small but important change to the `TMAExpectTxRewriter` class in the file `src/transform/warp_specialized_rewriter.cc`. The change initializes the `insert_in_evaluate_` boolean member to `true`.
* [`src/transform/warp_specialized_rewriter.cc`](diffhunk://#diff-3b0121eb3bc9b60c4f1b2aacc64bc682935d62afed8217bfc96bfd58765d403cL222-R222): Initialized the `insert_in_evaluate_` boolean member to `true` in the `TMAExpectTxRewriter` class.
=> [BugFix] Fix bug of missing MBarrierExpectTX

examples/native_sparse_attention/benchmark/benchmark_nsa_fwd.py, src/layout/layout.cc, src/layout/layout.h, src/layout/swizzle.cc, src/layout/swizzle.h, src/op/elem.cc, src/op/parallel.cc, src/transform/layout_inference.cc, testing/python/language/test_tilelang_language_reduce_max.py, testing/python/webgpu/test_webgpu_codegen.py
This pull request includes several changes to improve the `DebugOutput` methods in the layout-related classes and enhance layout inference checks. The most important changes include converting `DebugOutput` methods to return `std::string`, adding layout consistency checks, and minor code formatting improvements.
Improvements to `DebugOutput` methods:
* [`src/layout/layout.cc`](diffhunk://#diff-8e8b85e9396c3aaaf378020a15e4274510e97a4fb17c7c5ac7047596e1ca37c5L367-R381): The `DebugOutput` methods in `LayoutNode` and `FragmentNode` were modified to return `std::string` instead of printing directly to the console.
* [`src/layout/swizzle.cc`](diffhunk://#diff-345c4633d913e6c31c4b2137d9485fa0d4762dbd6efea08ac993c50acec15b0cL61-R66): The `DebugOutput` method in `SwizzledLayoutNode` was modified …
=> [Refactor] Refactor for Better Layout Conflict Handling

examples/flash_attention/example_mha_bwd_wgmma_pipelined.py, src/op/gemm.cc, src/op/gemm.h, src/transform/warp_specialized_rewriter.cc, tilelang/language/builtin.py, tilelang/language/gemm.py
This pull request introduces several changes to the `examples/flash_attention/example_mha_bwd_wgmma_pipelined.py` file to implement a flash attention mechanism. Additionally, it includes modifications in the `src/op/gemm.cc`, `src/op/gemm.h`, `src/transform/warp_specialized_rewriter.cc`, `tilelang/language/builtin.py`, and `tilelang/language/gemm.py` files to support new functionalities and improve the performance of the GEMM operations.
Key changes include:
* [`examples/flash_attention/example_mha_bwd_wgmma_pipelined.py`](diffhunk://#diff-81fa69a0f32d2eae21c82945f813a1d870c73abe1cdac5d083b2cf60cf733a1eR1-R345): Added functions for forward and backward flash attention operations, including preprocessing and postprocessing steps. The file also includes a reference implementation and …
=> [Dev] Implement FlashAttention3 Backward

src/op/gemm.cc, src/op/gemm.h, src/tl_templates/cuda/gemm_sm70.h, src/tl_templates/cuda/gemm_sm80.h, src/tl_templates/cuda/gemm_sm90.h, tilelang/language/gemm.py
- Introduced a new `zero_init` parameter to the GEMM function, allowing for optional zero initialization of the accumulator.
- Updated the GEMM implementation across various CUDA architectures to support the new parameter.
- Modified the Python interface for GEMM to include the `zero_init` argument, enhancing flexibility in kernel execution.
- Ensured compatibility with existing functionality while improving initialization control for performance optimization.
=> [Enhancement] Add zero initialization option to GEMM operations

src/target/codegen_cuda.cc
We should set the second parametr minBlockperSM for __launch_bounds__ to avoid C7508, just set it to 1 to make compiler happy.
=> [Enhancement][CUDA] Avoid C7508 for CUDA backend via assigning default value to `minBlocksPerMultiprocesor `

.gitignore, maint/scripts/docker_local_distribute.sh, maint/scripts/docker_pypi_distribute.sh, maint/scripts/pypi.Dockerfile, requirements-build.txt, setup.py, tilelang/jit/adapter/utils.py, tilelang/utils/tensor.py, tox.ini
As title.
Currently pypi wheels do not provide libraries required by libtvm_runtime.so and stuffs. This causes troubles like https://github.com/tile-ai/tilelang/issues/172 and a so missing error mentioned in wechat group.
This PR shell fix it.
=> [CI] Use auditwheel to generate manylinux wheels

benchmark/matmul/benchmark_matmul.py, tilelang/autotuner/__init__.py, tilelang/jit/adapter/cython/cython_wrapper.pyx, tilelang/jit/adapter/wrapper.py
- Updated `ref_program` in `benchmark_matmul.py` to remove the unused parameter `C`, simplifying the function signature.
- Changed logging level in `autotuner/__init__.py` from `INFO` to `DEBUG` for more detailed logging during autotuning.
- Modified the error handling in the autotuner to provide clearer messages and log errors at the debug level.
- Enhanced error reporting in the JIT adapter by adding detailed context to error messages in `cython_wrapper.pyx` when kernel calls fail.
=> [Bugfix] Fix auto tuning tma handling

src/op/elem.cc, src/op/elem.h, testing/python/language/test_tilelang_language_alias.py, testing/python/language/test_tilelang_language_clear.py, tilelang/jit/adapter/wrapper.py, tilelang/language/fill.py, tilelang/utils/__init__.py
Also a bug fix for issue #262 
This pull request includes several changes to enhance the handling of buffer regions, improve type annotations, and add new functionalities in the `fill` and `clear` functions. The most important changes are summarized below:
* [`src/op/elem.cc`](diffhunk://#diff-b41ad92a37e3f104b615eb0ec61a1d7af1c21ef178a5acb708e3b7391450cfb2R361-R403): Added support for handling `BufferLoadNode` instances and performing bounds checks on buffer regions in the `Fill` function.
* [`src/op/elem.cc`](diffhunk://#diff-b41ad92a37e3f104b615eb0ec61a1d7af1c21ef178a5acb708e3b7391450cfb2L375-R412): Updated `MakeSIMTLoop` to use the `region` array for loop variable ranges instead of directly using buffer shapes.
* [`src/op/elem.h`](diffhunk://#diff-7b294229e1942294a4e7352608794f95e151dd …
=> [Bugfix] Support `T.clear` for let binding

examples/flash_decoding/example_mha_inference.py, src/layout/layout.cc, src/op/elem.cc
- Removed unnecessary annotation for `lse_local_split` in the flash attention example to streamline the code.
- Updated the handling of `lse_local_split` to utilize parallel processing for better performance.
- Refactored kernel compilation and profiling logic to enhance clarity and maintainability in the flash attention example.
- Added a condition in `FragmentNode::IsEqual` to handle broadcast cases, improving the robustness of layout comparisons.
=> [Refactor] Improve flash attention example and layout comparison logic

tilelang/jit/adapter/ctypes/adapter.py, tilelang/jit/adapter/cython/cython_wrapper.pyx
Modified the `_warp_forward_from_prebuild_lib` method to check before accessing CUDA streams:
- Whether the current target platform is CUDA
- Whether CUDA is available
This fix has been tested in the following environments:
- Pure CPU environment (no NVIDIA driver)
```
(meson) yxc@yxc-MS-7B89:~/code/2503/tilelang_yxc$ python testing/python/cpu/test_tilelang_cpu_gemm.py
2025-03-24 01:21:55 [TileLang:INFO]: No cached version found for cython jit adapter, need to compile...
2025-03-24 01:21:55 [TileLang:INFO]: Compiling cython jit adapter...
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.12.3, pytest-8.3.5, …
```
=> [Bugfix]Add CUDA availability check in CtypesKernelAdapter

tilelang/cache/kernel_cache.py
- Changed the cache key generation to use the serialized script of the function instead of the function object itself, improving the uniqueness of cache keys.
Also a fix for issue #271
=> [Refactor] Update cache key generation in KernelCache

README.md
This pull request includes a change to the `README.md` file. The change removes the citation section, which provided a BibTeX entry for citing the TileLang project.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L230-L241): Removed the citation section, which included a BibTeX entry for citing the TileLang project.
=> [Doc] Remove citation page

src/transform/layout_inference.cc, testing/python/dynamic/test_tilelang_dynamic_symbolic.py
- Introduced the ParallelLoopTransformer class to improve the handling of parallel loops in layout inference.
- Enhanced the analysis of loop variables and their extents, allowing for more accurate index range calculations.
- Added a BufferAccessCollector to gather buffer access information, ensuring correct index mapping and condition handling.
- Updated the LayoutInference pass to utilize the new transformer, improving overall performance and accuracy in loop transformations.
=> [Feature] Implement ParallelLoopTransformer for enhanced loop analysis

src/tl_templates/cuda/common.h
- Added conditional compilation for BFLOAT16 atomic operations to ensure compatibility with CUDA architectures greater than 7.5.
- Improved code clarity by organizing the AtomicAdd functions and adding relevant comments for better understanding.
=> [Enhancement] Update AtomicAdd functions for BFLOAT16 in common.h

tilelang/carver/roller/node.py
The `is_reduction` method was not correctly invoked, resulting in the buffer cache eligibility check always passing, which may lead to unnecessary cache statistics.
=> [Bugfix] Correct method call for block reduction check when analyzing memory footprint

src/transform/loop_vectorize.cc, src/transform/loop_vectorize_dynamic.cc, tilelang/engine/phase.py, tilelang/transform/__init__.py
* Add `LoopVectorizeDynamic` pass to support tail split with dynamic shape specially.
* Refactor `loop_vectorize.cc` to be dedicated to static stuff.
* Fix the bug of shape bound check when meeting `T.if_then_else` expressions.
=> [Dynamic Symbolic] Refactor passes with dynamic symbolic and check shape bound precisely

examples/blocksparse_gemm/example_blocksparse_gemm.py, tilelang/autotuner/__init__.py, tilelang/engine/param.py, tilelang/profiler/__init__.py, tilelang/utils/tensor.py
This PR addresses several issues identified in the `tilelang.autotuner` module, primarily discovered while running `example_blocksparse_gemm.py`.
- **Logging Configuration:** Reworked the autotuner's logging setup to correctly route `DEBUG` messages to `autotuner.log` and `INFO+` messages to the console, resolving problems where debug logs were missed.
- **Boolean Tensor Generation:** Corrected `get_tensor_supply` to properly generate tensors with `torch.bool` dtype, avoiding out-of-bounds errors.
- **Input Tensor Regeneration:** Modified the autotuner to always regenerate JIT input tensors for each configuration trial, preventing errors caused by reusing potentially incompatible cached inputs from previous trials.
- **Example Update:** Updated `example_blocksparse_gemm.py` to align with …
=> [Bugfix] Resolve autotuner bugs for blocksparse GEMM example

examples/elementwise/elementwise_add.py, examples/norm/rms_norm.py
The use of profiler.mod in the example scripts elementwise_add.py and rms_norm.py causes an error when passed to profiler.do_bench(): `AttributeError: 'Profiler' object has no attribute 'mod'`
Replaced profiler.mod with profiler.adapter, which correctly references the backend module for benchmarking. This change resolves the error and allows the examples to run as expected.
=> [Bugfix] Replace profiler.mod with profiler.adapter to fix AttributeError

src/tl_templates/cuda/gemm.h, src/tl_templates/cuda/gemm_sm89.h
- Introduced conditional inclusion of "gemm_sm89.h" for CUDA architectures 8.9 and above, enhancing compatibility with newer hardware.
- This change ensures that the GEMM template can leverage optimizations specific to the 8.9 architecture, improving performance for users with compatible GPUs.
=> [Enhancement] Add support for CUDA architecture 8.9 in GEMM template

examples/flash_decoding/example_gqa_decode.py, src/transform/loop_vectorize_dynamic.cc
This pull request includes changes to improve the memory allocation and performance tuning in `examples/flash_decoding/example_gqa_decode.py`, as well as a minor cleanup in `src/transform/loop_vectorize_dynamic.cc`.
Memory allocation improvements:
* Changed `lse_local_split` to use `T.alloc_var` instead of `T.alloc_local` to improve memory allocation efficiency.
* Simplified the update of `lse_local_split` and `lse_logsum_local` to reduce redundant assignments.
Performance tuning:
* Added a new function `get_heuristic_config` to dynamically determine CUDA device properties and set configuration parameters accordingly. This change ensures optimal performance based on the device's capabilities.
* Updated the `flashattn` function call to use the configuration dictionary returned by …
=> [Bugfix] Fix layout conflict issue for gqa decoding examples

src/transform/if_stmt_binding.cc
This pull request includes a change to the `IfStmtBindingRewriter` class in the `src/transform/if_stmt_binding.cc` file. The change modifies how `then_case` and `else_case` are handled within the `VisitStmt_` method.
Handling of `then_case` and `else_case`:
* [`src/transform/if_stmt_binding.cc`](diffhunk://#diff-6600052496f40bdbba24c6390a66006fd2eef3b013e0fe7eee13aceead0f398bL34-R38): Updated the `VisitStmt_` method to use `VisitStmt` for `then_case` and conditionally apply `VisitStmt` to `else_case` if it is defined.
=> [Bugfix] Fixed the handling logic of IfThenElseNode in if_stmt_binding

src/op/reduce.cc, src/transform/if_stmt_binding.cc
Improvements to target architecture handling:
* [`src/op/reduce.cc`](diffhunk://#diff-6db4f8a0f03dffeb4b8b493182b3754cc170d550bb6ea71ca472ced6320c8868L164-R166): Added a check to ensure the "arch" attribute is present before comparing it to "sm_90".
=> [Bugfix] Fix logic error in ReduceOp when handling CUDA architecture

tilelang/carver/arch/cuda.py, tilelang/carver/arch/driver/__init__.py, tilelang/carver/arch/driver/cuda_driver.py
This pull request introduces a new CUDA driver module and integrates it into the existing CUDA architecture code. The changes include importing the new driver, updating device initialization, and adding various utility functions for CUDA device properties.
* [`tilelang/carver/arch/cuda.py`](diffhunk://#diff-e98d1e9c25e5267000d91281042f3a63195cab474b36d20592f4ecbae837f1aaR8): Imported the new `cuda_driver` module and updated the device initialization to use `cuda_driver` functions for getting device name and shared memory per block. [[1]](diffhunk://#diff-e98d1e9c25e5267000d91281042f3a63195cab474b36d20592f4ecbae837f1aaR8) [[2]](diffhunk://#diff-e98d1e9c25e5267000d91281042f3a63195cab474b36d20592f4ecbae837f1aaR119-R123)
* [`tilelang/carver/arch/driver/__init__.py`](diffhunk://#diff-0bf7175411 …
=> [CostModel] Introduce cuda driver api to get precise shared memory capacity

examples/cast/example_per_token_cast_to_fp8.py, examples/cast/example_triton_cast_to_fp8.py, src/op/reduce.cc, src/op/reduce.h, tilelang/language/__init__.py, tilelang/language/reduce.py
This pull request introduces a new feature for per-token-group quantization to float8 and adds support for a new reduction type, `absmax`. The changes include new example scripts, modifications to the reduction operation, and additional utility functions.
* [`examples/cast/example_per_token_cast_to_fp8.py`](diffhunk://#diff-59fa27f1ae846846242c58721e6387c0135ed1f516ad8f92a73cac13fbbdd605R1-R125): Added a new example script demonstrating per-token-group quantization to float8 using Tile-lang.
* [`examples/cast/example_triton_cast_to_fp8.py`](diffhunk://#diff-da2069293d16bdeec5542151b04543071fbc79f3c29f8b08cbafbaf77ffefd40R1-R186): Added a new example script demonstrating per-token-group quantization to float8 using Triton.
* [`src/op/reduce.cc`](diffhunk://#diff-6db4f8a0f03dffeb4b8b493182b3 …
=> [Dev] Add FP8 Quantization Examples and Absolute Maximum Reduction Operation Support

src/tl_templates/cuda/common.h
Without the patch, calling `T.abs` on `cutlass:half_t` will trigger:
```
/tmp/tmpu264lyg1.cu(12): error: no instance of overloaded function "__habs" matches the argument list
argument types are: (cutlass::half_t)
val[0] = __habs(val[0]);
/usr/local/cuda-12.4/bin/../targets/x86_64-linux/include/cuda_bf16.hpp(3509): note #3326-D: function "__habs(__nv_bfloat16)" does not match because argument #1 does not match parameter
static __attribute__((host)) __attribute__((device)) __inline__ __nv_bfloat16 __habs(const __nv_bfloat16 a)
^
/usr/local/cuda-12.4/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(3252): note #3326-D: function "__habs(__half)" does not match because argument #1 does not match parameter
static __attribute__((host)) __attribute__((device)) __inline__ __half __habs(const …
```
=> [Bugfix] add a patch to fix T.abs on float16

pyproject.toml, src/op/gemm.cc, src/target/codegen_hip.cc, src/target/rt_mod_hip.cc, src/tl_templates/hip/common.h, src/tl_templates/hip/debug.h, src/tl_templates/hip/gemm.h, testing/python/amd/test_tilelang_test_amd.py, tilelang/__init__.py, tilelang/contrib/rocm.py, tilelang/engine/__init__.py, tilelang/jit/adapter/libgen.py, tilelang/jit/adapter/wrapper.py
This pull request includes various changes to improve the functionality and compatibility of the Tile-AI project, particularly focusing on the HIP (Heterogeneous-Compute Interface for Portability) backend. The most important changes include adding support for new data types, enhancing debug capabilities, and refining matrix operations.
* [`src/tl_templates/hip/common.h`](diffhunk://#diff-688f4edb061910df1c04c5d483e0d7283b7bd5aadb4479bdff7f39fad1f6c0f9R46-R65): Added definitions for `bfloat16_t` and related vector types, and redefined `half_t` to `float16_t` for better compatibility. [[1]](diffhunk://#diff-688f4edb061910df1c04c5d483e0d7283b7bd5aadb4479bdff7f39fad1f6c0f9R46-R65) [[2]](diffhunk://#diff-688f4edb061910df1c04c5d483e0d7283b7bd5aadb4479bdff7f39fad1f6c0f9L38)
* …
=> [AMD] Adapt rocm and support `T.gemm` with transpose_b=False for amd backend

src/tl_templates/hip/gemm.h, testing/python/amd/test_tilelang_test_amd.py
…EMM with transpose options
- Introduced `matmul_rs` function for flexible matrix multiplication with optional transposition.
- Added `run_gemm_rs` function to facilitate testing of the new matrix multiplication implementation.
- Expanded test coverage for GEMM with additional cases for transposition configurations.
- Corrected index usage in `gemm.h` to ensure proper matrix layout handling.
These changes enhance the GEMM functionality and improve testing capabilities for various matrix configurations.
=> [AMD] Support `Transpose_A=True`  and GEMM_RS for hip backend

examples/norm/rms_norm.py
- Introduced a new local fragment for squared values to improve performance.
- Updated the computation of the RMS normalization to use the new fragment, enhancing memory efficiency.
- Refactored the final multiplication step to operate on the local fragment instead of shared memory.
- Added a configuration option to the kernel compilation for better control over TMA lowering.
These changes enhance the efficiency and clarity of the RMS normalization implementation.
=> [Refactor] Optimize RMS normalization kernel in rms_norm.py

docs/deeplearning_operators/gemv.md
This pull request includes a change to the `gemv.md` file. The changes add heading level to title in the document to make the heading level right.
=> [Doc] Fix typo and heading level in GEMV tutorial

examples/cast/example_group_per_split_token_cast_to_fp8.py
Implements FP8 type conversion functionality for grouped per-split tokens. The script includes several helper functions for handling tensor TMA alignment and FP8 conversion, enhancing support for FP8 data types and providing performance benchmarks. This change provides users with more flexible examples of FP8 operations.
=> [Dev] Add Group Cast FP8 Example

src/op/op.cc, tilelang/language/copy.py
Enhance error checking in RegionOp and buffer_load_to_tile_region
- Added detailed error messages to the index size check in `RegionOp` to aid debugging.
- Implemented a check in `buffer_load_to_tile_region` to ensure the length of indices matches extents, with a fallback to expand extents if necessary. This improves robustness in handling buffer loads with mismatched dimensions.
=> [Enhancement] Support region padding when convert buffer load to buffer region

src/layout/gemm_layouts.cc, testing/python/amd/test_tilelang_test_amd.py
This pull request includes changes to the `src/layout/gemm_layouts.cc` and `testing/python/amd/test_tilelang_test_amd.py` files, focusing on improving the layout and functionality of GEMM operations and enhancing the testing framework for AMD.
* [`src/layout/gemm_layouts.cc`](diffhunk://#diff-402e906ccbf0bec59a2db319e19a1525cc7d6efd11523bf1b6f2a1462b64e29cL185-R186): Adjusted the `makeGemmFragmentACDNA` function to correct the layout repetition parameters, ensuring proper alignment and replication of GEMM fragments.
* [`testing/python/amd/test_tilelang_test_amd.py`](diffhunk://#diff-8a9a2a591137c8e849559bda1e5ac8de88f871c10a6d3b6ab31e0d4eb9fbb812L134-R138): Reformatted the `main` function in `matmul_rs` for better readability and consistency.
* …
=> [Bugfix] Fix Transposed Fragment Layout for amd GEMM_RS matrix core 

examples/gemm/example_gemm.py, examples/gemm/example_gemm_intrinsics.py, testing/python/autotune/test_tilelang_autotune_decorator.py, testing/python/kernel/test_tilelang_kernel_convolution.py, testing/python/primitives/test_tilelang_primitives_mma.py, tilelang/autotuner/__init__.py, tilelang/utils/tensor.py
- Modified `example_gemm_intrinsics.py` to enhance matrix multiplication configurations, increasing warp sizes and adjusting data types for better performance.
- Updated the kernel compilation process to utilize the new `tilelang.compile` method and improved latency measurement with the profiler.
- Refactored `example_gemm.py` to include a new autotuning configuration and ensure consistency in latency checks against reference results.
- Adjusted tensor supply generation in `tilelang/utils/tensor.py` to use `torch.randn` for better randomness in tensor initialization.
- Enhanced the `JITContext` in `tilelang/autotuner/__init__.py` to replace the profiler with a kernel instance for performance measurement, improving the overall structure of the autotuner.
=> [AutoTune] Refactor AutoTuneArtifact to utilize kernel as context instead of profiler

tilelang/language/frame.py, tilelang/language/kernel.py
This pull request introduces changes to `tilelang/language/frame.py` and `tilelang/language/kernel.py` to ensure thread safety by using thread-local storage for frame stacks. Additionally, a new method is added to the `FrameStack` class in `tilelang/language/kernel.py`.
Thread safety improvements:
* [`tilelang/language/frame.py`](diffhunk://#diff-389cd48e2e02bc14e6545fd1832a7a0658defbe037acca12cb035e2644892d56R12): Replaced the global `_let_frame_stack` with a thread-local `_local_let` to store the stack, and updated methods to use `_get_let_stack()` for accessing the stack. [[1]](diffhunk://#diff-389cd48e2e02bc14e6545fd1832a7a0658defbe037acca12cb035e2644892d56R12) [[2]](diffhunk://#diff-389cd48e2e02bc14e6545fd1832a7a0658defbe037acca12cb035e2644892d56L100-R109) …
=> [Refactor] Implement thread-local storage for FrameStack in frame.py and kernel.py

examples/deepseek_mla/benchmark_mla.py
This pull request includes several changes to the `examples/deepseek_mla/benchmark_mla.py` file to improve the import structure and simplify the code. The most important changes include removing unnecessary imports, moving imports inside functions, and updating function calls.
Improvements to import structure:
* Removed unused imports `flashinfer`, `flash_mla_with_kvcache`, and `get_mla_metadata` from the top of the file.
Simplification of code:
* Moved the import of `flash_mla_with_kvcache` and `get_mla_metadata` inside the `run_flash_mla` function.
* Moved the import of `flashinfer` inside the `run_flash_infer` function and added a comment about installation.
* Updated the function call to `kernel` in `flash_mla_tilelang` to use `kernel.func`.
=> [Typo] Replace `kernel.func` with `kernel` in mla benchmark scripts

src/op/builtin.cc, src/op/builtin.h, src/transform/warp_specialized_rewriter.cc, testing/python/pass_config/test_tilelang_pass_config_disable_warp_specialized.py, testing/python/transform/test_tilelang_transform_multi_version_buffer.py, tilelang/engine/phase.py, tilelang/jit/__init__.py
This pull request introduces several changes to the TVM project, focusing on adding a new configuration option, modifying the `WarpSpecializedRewriter` class, and updating related test files. The most important changes include adding the `kDisableWarpSpecialized` configuration option, enhancing the `WarpSpecializedRewriter` class to support this new option, and updating the test and phase files accordingly.
* [`src/op/builtin.cc`](diffhunk://#diff-39f3332b8026cdf6f2a0bcd6b507e46f4347e6e071b6a76668d4b7cec4b8f73eR23): Added a new configuration option `kDisableWarpSpecialized`.
* [`src/op/builtin.h`](diffhunk://#diff-77f0be35bfe359f85f32631aeb22db3337381c1da1676eca0da6c8588de94964L20-R21): Defined the new configuration option `kDisableWarpSpecialized`.
* …
=> [Enhancement] Support pass config `disable_warp_specialize` to disable auto specialization on hopper

tilelang/jit/adapter/wrapper.py
- Updated the error handling logic in `PREDEF_ATTRIBUTE_SET_DYNAMIC_MEMORY_HIP` to check if the dynamic shared memory size exceeds the maximum limit of 65536.
- Improved error message clarity by specifying the function name and the attempted size, ensuring better debugging information.
- Ensured the function returns 0 upon successful setting of the dynamic shared memory size.
=> [Bugfix] Correct dynamic shared memory size error handling in HIP 

examples/deepseek_mla/example_mla_decode.py, examples/deepseek_mla/example_mla_decode_amd.py, src/layout/gemm_layouts.cc, tilelang/jit/adapter/wrapper.py
This pull request introduces a new example file for decoding using the Tile-AI library and makes some minor improvements to existing code for better error handling and code consistency. The changes are primarily focused on adding a new functionality and refining error messages.
New functionality:
* [`examples/deepseek_mla/example_mla_decode_amd.py`](diffhunk://#diff-7796a945e5de974762af560b70ed4ac475d7457e536a0758082087fe76e4000aR1-R293): Added a new example file that demonstrates how to use the Tile-AI library for decoding with attention mechanisms. This includes defining several macros and functions for the flash attention mechanism and providing a reference program for comparison.
Error handling improvements:
* [`src/layout/gemm_layouts.cc`](diffhunk://#diff-402e906ccbf0bec59a2db319e19a …
=> [AMD] Implement Deepseek MLA for AMD 

src/layout/gemm_layouts.cc, src/layout/layout.h, src/op/gemm.cc, tilelang/autotuner/__init__.py
This pull request includes changes to enhance the GEMM fragment creation functions and improve the auto-tuning process in the `tilelang` module. The most important changes include adding an `element_size` parameter to GEMM fragment functions and enhancing timeout handling in the auto-tuner.
Enhancements to GEMM fragment creation:
* [`src/layout/gemm_layouts.cc`](diffhunk://#diff-402e906ccbf0bec59a2db319e19a1525cc7d6efd11523bf1b6f2a1462b64e29cL176-R177): Added an `element_size` parameter to the `makeGemmFragmentACDNA` function to accommodate different element sizes.
* [`src/layout/layout.h`](diffhunk://#diff-6294e9e63d3b1b3abaab214671f414ccba47aab33c0c5373f51a87460cadcc98L152-R153): Updated the `makeGemmFragmentACDNA` function declaration to include the `element_size` parameter.
* …
=> [Bugfix] Fix compilation issues for amd cdna element size check

tilelang/jit/adapter/utils.py
This pull request includes a modification to the `match_declare_kernel` function in the `tilelang/jit/adapter/utils.py` file to improve the pattern matching for kernel declarations.
Pattern matching improvement:
* [`tilelang/jit/adapter/utils.py`](diffhunk://#diff-6f11c60f8bb9fa7b730d84353f032c859f799a0b1399cabb6f0939c370b8abe1L35-R35): Updated the regular expression pattern in the `match_declare_kernel` function to account for optional `__launch_bounds__` annotations in kernel declarations.
=> [AMD] Support FlashMLA with num split template for AMD gpus

examples/deepseek_mla/amd/benchmark_mla_decode_amd_tilelang.py, examples/deepseek_mla/amd/benchmark_mla_decode_amd_torch.py, examples/deepseek_mla/amd/benchmark_mla_decode_amd_triton.py, tilelang/autotuner/__init__.py
This pull request includes several changes to the `examples/deepseek_mla/amd/benchmark_mla_decode_amd_tilelang.py` file, which was renamed from `examples/deepseek_mla/example_mla_decode_amd.py`, as well as updates to the `tilelang/autotuner/__init__.py` file. The changes focus on renaming functions, modifying tuning parameters, and improving the auto-tuning functionality.
Function renaming and parameter updates:
* Renamed the function `flashattn` to `flashmla_decode` and updated its references accordingly. [[1]](diffhunk://#diff-31405fb3693e5f813663e432cae0d53cce618699cf836917ac8a766f8b9cfb72L15-R15) [[2]](diffhunk://#diff-31405fb3693e5f813663e432cae0d53cce618699cf836917ac8a766f8b9cfb72L281-R345)
* Changed the `policy` parameter in the `T.gemm` method calls from `T.GemmWarpPolicy.FullCol` …
=> [MLA][AMD] Add amd mla benchmarking 

examples/blocksparse_gemm/example_blocksparse_gemm.py, tilelang/autotuner/__init__.py
Currently the autotuner calculates the `max_workers` for its `ThreadPoolExecutor` (used for concurrent kernel compilation) based on `os.cpu_count()`.
However, `os.cpu_count()` reflects the total number of CPUs available on the *system*, which doesn't necessarily reflect the number of cores the *current process* is actually allowed to use. The mismatch is common in containerized environments or when CPU affinity is set using tools like `taskset`.
Attempting to use more worker threads than available CPUs can lead to system thrashing and slow down the compilation process rather than accelerating it.
I think a better approach is to use `len(os.sched_getaffinity(0))` to get the number of CPUs that the process is actually available to use …
=> [Bugfix] Adjust Autotuner threadpool `max_workers` limit to available CPUs

src/transform/legalize_safe_memory_access.cc, src/transform/vectorize_loop.cc, tilelang/engine/phase.py
- Introduced a check in the GlobalMemChecker to determine if the index used in memory access has any variable components, enhancing the safety of memory access validation.
- Updated the condition handling in store operations to ensure that only boolean conditions are processed, improving type safety and error handling in memory operations.
=> [Typo] Remove debug print

tilelang/engine/phase.py, tilelang/jit/adapter/cython/adapter.py
This pull request includes several changes to the `tilelang` project aimed at improving the efficiency and reliability of the code. The changes primarily focus on removing unnecessary print statements, adding file locking mechanisms, and using temporary files to ensure atomic operations during compilation.
* [`tilelang/engine/phase.py`](diffhunk://#diff-d0919e6c22b4d85ff6c5a0a9f34b53bc9415d8c61dc84e9993841b10d14e44a5L92): Removed an unnecessary `print` statement from the `OptimizeForTarget` function to clean up the output.
* [`tilelang/jit/adapter/cython/adapter.py`](diffhunk://#diff-fb6f070e77115039cffa90aea9d733c451c961c1c517ad15f5f58487a4ab1548R65-R81): Added file locking using `fcntl` to prevent concurrent access issues when loading cached libraries in the `get_cached_lib` function.
* …
=> [Bugfix] Add filelock for cython build

src/transform/legalize_safe_memory_access.cc, tilelang/jit/adapter/cython/adapter.py
This pull request includes changes to the `src/transform/legalize_safe_memory_access.cc` file to clean up the code by removing unnecessary logging statements.
Codebase cleanup:
* [`src/transform/legalize_safe_memory_access.cc`](diffhunk://#diff-d9e675b8eb6e382847a1b542e623ee7ebe4afe1ad470f6cf983e6330e795fcb0L173-L181): Removed `LOG(INFO)` statements that output conditions, store, and value information within the `SafeMemorysRewriter` class.
=> [Refactor] Remove debug message in pass legalize_safe_memory_access

src/transform/flatten_buffer.cc, tilelang/engine/phase.py
This pull request includes updates to a submodule and a correction in a function within the `tilelang/engine/phase.py` file.
Submodule update:
* [`3rdparty/tvm`](diffhunk://#diff-fa909c93fe94e9aa04c9e7f19e5754a2bb274678ad5c6275ee4bf54c6f9b1066L1-R1): Updated the submodule commit reference to the latest commit.
Function correction:
* [`tilelang/engine/phase.py`](diffhunk://#diff-d0919e6c22b4d85ff6c5a0a9f34b53bc9415d8c61dc84e9993841b10d14e44a5L57-R57): Corrected the call to `FlattenBuffer` by changing its namespace from `tilelang.transform` to `tir.transform` in the `OptimizeForTarget` function.
=> [Revert] Revert modifications for pass FlattenBuffer

src/transform/pipeline_planning.cc
This pull request introduces several enhancements and bug fixes to the `PipelinePlanner` class in `src/transform/pipeline_planning.cc`. The changes improve the handling of pipeline stages, annotations, and memory copy operations.
* Added a new `PipelineStageInfo` struct to store detailed information about each pipeline stage, including buffer regions read and written, original and current order, stage number, and memory copy operation status.
* Modified the `VisitStmt_` method to handle `tl_pipeline_order` and `tl_pipeline_stage` annotations, updating the loop annotations accordingly and setting the `software_pipeline_order` and `software_pipeline_stage` attributes.
* Enhanced the pipeline stage ordering logic to account for stages used by copy operations, assigning stage 0 to such stages …
=> [Pipeline][Enhancement] Add copy_prepare stage to support mask and index caching

src/op/parallel.cc
Added detailed error messages in the InferLayout method to provide better context when layout conflicts occur. This includes the body of the operation that triggered the error, aiding in debugging and layout validation.
=> [Enhancement] Report Error Body in ParallelOp Layout Inference

src/transform/layout_inference.cc, src/transform/loop_vectorize.cc, tilelang/engine/param.py
This pull request includes several changes to improve the layout inference and loop vectorization processes, as well as updates to type-checking methods in the `tilelang` engine. The most important changes are detailed below:
* Added a check to detect whether a buffer store targets a "local" buffer, which justifies skipping thread binding for register-local buffers in parallel loops. (`src/transform/layout_inference.cc`)
* Removed unnecessary comments and simplified logic in the `Plan` method to always enable vectorization. (`src/transform/loop_vectorize.cc`)
* Simplified the binding and transformation of expressions in the `IndiceCanVectorize` function to improve readability and maintainability. (`src/transform/loop_vectorize.cc`)
* Refactored the `is_unsigned`, `is_float8`, and …
=> [Bugfix] Support `T.Parallel` with local register assignment 

src/target/codegen_hip.cc, src/tl_templates/hip/common.h, src/tl_templates/hip/gemm.h, testing/python/amd/test_tilelang_test_amd.py
This adds preliminary bfloat16 for AMD, tested on a MI250. 
We generalize the `tl:gemm_ss` operation for HIP to work for both fp16 and bf16.
This has only been tested on a version of the `examples/quickstart.py` script:
```python
import tilelang
import tilelang.language as T
from tilelang.intrinsics import (
make_mma_swizzle_layout as make_swizzle_layout,)  # noqa: F401
import torch
tl_dtype = "bfloat16"
torch_dtype = torch.bfloat16
def matmul(M, N, K, block_M, block_N, block_K, dtype=tl_dtype, accum_dtype="float"):
@T.prim_func
def main(
A: T.Tensor((M, K), dtype),
B: T.Tensor((K, N), dtype),
C: T.Tensor((M, N), dtype),
):
with T.Kernel(T.ceildiv(N, block_N), T.ceildiv(M, block_M), threads=128) as (bx, by):
A_shared = T.alloc_shared((block_M, block_K), dtype)
B_shared = …
```
=> Add preliminary support for bf16 for AMD

docs/get_started/Installation.md
There are some typos in the documentation that make the provided build instructions incorrect.
Changes:
* Removed sudo as the provided image does not have sudo
* Changed tileLang to tilelang
=> [Documentation] Fix Installation Documentation

src/transform/common/loop_fusion_utils.h, src/transform/loop_vectorize.cc
This pull request includes updates to a submodule, enhancements to loop fusion logic, and improvements to vectorization handling. The most significant changes focus on ensuring correctness in loop fusion by checking loop extents and optimizing vectorization by simplifying expressions earlier in the process.
* Updated the `tvm` submodule to a new commit (`b56a1df6f3e41c6b6da019786b88d73ee9a0d378`) to incorporate the latest changes.
* In `src/transform/common/loop_fusion_utils.h`, added logic to check if the extent of loops in the fusion chain is a power of 2. If the extent is not a constant integer or not a power of 2, the fusion process is skipped to ensure correctness.
* In `src/transform/loop_vectorize.cc`, moved the simplification of vectorized expressions earlier in the process to …
=> [Enhancement] Remove redundant recursive rewrite rule for FloorDiv in RewriteSimplifier

requirements-dev.txt, requirements-test.txt, requirements.txt
This pull request updates a submodule and removes unused dependencies from the development and testing requirements files. Below is a breakdown of the most important changes:
* Updated the `tvm` submodule to a new commit (`17ab6489dfd6b219db6f72cf5bec5e2c1c5c8690`) from the previous one (`b56a1df6f3e41c6b6da019786b88d73ee9a0d378`).
* Removed the `decorator` and `attrs` packages from the `requirements-dev.txt` file, as they are no longer needed. [[1]](diffhunk://#diff-2b4945591edfeaa4cf4d3f155e66d4b43d1bda7a55d881d5cf3107f1b05abbbcL9) [[2]](diffhunk://#diff-2b4945591edfeaa4cf4d3f155e66d4b43d1bda7a55d881d5cf3107f1b05abbbcL20)
* Removed the `decorator` and `attrs` packages from the `requirements-test.txt` file, aligning the test dependencies with the updated requirements. …
=> [Refactor] Phaseout python dependency `attrs` and `decorator`

examples/deepseek_mla/experimental/example_mla_decode_kv_fp8.py, examples/quickstart.py, src/op/bulk_copy.cc, tilelang/engine/phase.py, tilelang/jit/adapter/wrapper.py
This pull request introduces a new experimental implementation for flash attention in `example_mla_decode_kv_fp8.py`, along with improvements to memory handling, error reporting, and pipeline optimization across various files. The key changes are grouped by their themes below:
* Added a new experimental implementation of flash attention in the file `examples/deepseek_mla/experimental/example_mla_decode_kv_fp8.py`. This includes a kernel function (`flashattn`) written using the TileLang DSL, a reference program for validation, and a benchmarking script to measure performance in terms of latency and TFlops.
* Updated `src/op/bulk_copy.cc` to ensure that the `instruction_dim` for shared memory (`smem_box`) does not exceed 256. If it is 512, the copy operation is split into two parts, and a …
=> [Bugfix] Support larger than 256 box size tma copy

tilelang/contrib/nvcc.py, tilelang/jit/adapter/libgen.py
* Introduced a new function `get_nvcc_compiler` in nvcc.py to obtain the path to the nvcc compiler.
* Updated LibraryGenerator to use `get_nvcc_compiler` instead of hardcoding the nvcc command, improving maintainability and flexibility.
=> [Enhancement] Add get_nvcc_compiler function to retrieve nvcc path

src/layout/layout.cc, src/layout/layout.h, src/op/elem.cc, src/op/gemm.cc, src/op/op.h, src/op/parallel.cc, src/op/reduce.cc, src/transform/layout_inference.cc, src/transform/loop_partition.cc, src/transform/loop_partition.h, src/transform/lower_tile_op.cc, testing/python/language/test_tilelang_language_mask_op.py, tilelang/engine/phase.py, tilelang/transform/__init__.py
This pull request introduces significant updates to the handling of thread bounds and layout inference across multiple files. Key changes include replacing `block_size` with `thread_bounds`, adding new methods to manage thread ranges in the `FragmentNode` class, and refactoring layout inference logic to improve accuracy and maintainability. Additionally, it introduces a new utility for collecting thread bounds and updates several classes to use `IRVisitorWithAnalyzer` instead of `StmtExprVisitor`.
* Replaced `block_size` with `thread_bounds` in `LowerArgs` and `LayoutInferArgs` structures, and updated all related method calls to reflect this change. (`src/op/op.h` [[1]](diffhunk://#diff-cd00e66a3ec316061c402f865f5883c682ca8521ff27c4fe830591b2b761cdd0L50-R50) …
=> [Enhancement] Support Auto Layout Inference and Parallelism with variable constraint

tilelang/jit/adapter/cython/adapter.py
Many users install Cython into their local site package or venv, without this, they have to use `export PATH=/path/to/Cython/` to contain Cython executable, we want to do this automatically as like `pip install Cython` will install the directory like `~/.local/bin`. 
The order will be `venv`, then `user site directory` then `system directory`, this is also a reasonable directory order to search.
=> [Enhancement] Support to find Cython path more automatically

src/op/parallel.cc
* Updated the layout inference in ParallelOp to improve the selection of source buffers for layout accuracy.
* Introduced logic to choose the read source buffer based on the number of indices, ensuring more precise layout inference.
* Refactored the loop handling to maintain clarity and improve the overall robustness of the layout inference process.
=> [Refactor] Enhance layout inference logic in ParallelOp

src/transform/pipeline_planning.cc
* Introduced logic to check for TMA+WS enablement based on annotations in the pipeline planning stage.
* Enhanced the handling of `order_anno` and `stage_anno` to determine if TMA+WS is activated, improving flexibility in loop processing.
* Refactored the existing code to maintain clarity while integrating the new feature.
=> [Enhancement] Add TMA+WS support in pipeline planning logic

src/op/reduce.cc, src/op/reduce.h, src/tl_templates/cuda/reduce.h, testing/python/language/test_tilelang_language_cumsum.py, testing/python/language/test_tilelang_language_reduce_sum.py, tilelang/language/__init__.py, tilelang/language/reduce.py, tilelang/utils/tensor.py
This pull request introduces a new cumulative sum (`cumsum`) operation in the TileLang framework, along with its implementation, integration, and testing. The changes include adding the `CumSumOp` operator, implementing the CUDA kernel for `cumsum`, updating the TileLang language interface, and adding comprehensive tests for both shared memory and fragment scopes.
* **Operator Implementation:**
- Added `CumSumOp` class in `src/op/reduce.h` and its corresponding registration in `src/op/reduce.cc`. This operator supports cumulative summation along a specified dimension, with an option for reverse mode. It includes methods for lowering to target-specific code and layout inference. [[1]](diffhunk://#diff-6db4f8a0f03dffeb4b8b493182b3754cc170d550bb6ea71ca472ced6320c8868R243-R292) …
=> [Language] Support tile operator `T.cumsum`

testing/python/language/test_tilelang_language_copy.py
This pull request updates a submodule and introduces a new test file to validate functionality for copying tensors using the TileLang library. The most significant changes include updating the `tvm` submodule and adding a new test for TileLang's tensor copy functionality.
* Updated the `tvm` submodule to the latest commit `b16c9f298bc37fa502ffdb2ea809c2793e2a0bd6` to incorporate upstream changes.
* Added `testing/python/language/test_tilelang_language_copy.py` to test tensor copy functionality with TileLang. This includes:
- A `tilelang_copy` function that defines a TileLang kernel for copying tensors.
- A `run_tilelang_copy` function to compile and execute the kernel, validating the results using PyTorch.
- A `test_tilelang_copy` function to run multiple test cases with varying tensor …
=> [Bugfix] Fix a bug for simplifier

src/op/elem.cc, src/op/parallel.cc, tilelang/jit/adapter/wrapper.py
This pull request introduces enhancements to layout inference and optimization for parallel operations, along with a minor change in a Python wrapper file. The most significant updates involve adding support for multiple inference levels and improving layout computation logic.
* **Added multiple inference levels for layout optimization**: Introduced `InferLevel` with three levels (`kStrict`, `kCommon`, `kFree`) to control the aggressiveness of layout inference and optimization. Each level has distinct behavior, ranging from conservative to highly permissive. This change is documented in `ParallelOp::InferLayout`.
* **Updated layout inference logic in `ParallelOp::InferLayout`**: Enhanced the method to handle cases where `read_source_buffer` is defined, improving layout computation …
=> [Layout] Enhance layout inference pass

src/op/gemm.cc, src/op/parallel.cc
This pull request refines layout inference logic in the `Gemm` and `ParallelOp` operations by addressing block size calculations, simplifying conditions, and cleaning up unused or commented-out code. These changes aim to improve code clarity and maintainability while ensuring correctness in layout inference.
* Adjusted block size calculation to account for the `min` value in `T.thread_bounds`, ensuring accurate computation of block size. (`src/op/gemm.cc`, [src/op/gemm.ccL167-R168](diffhunk://#diff-5cbeefe6d2ab80fbd44350603133779b381d613ca2f5b4f4a6bf89dbe98b6d2cL167-R168))
* Removed a warning log and the associated condition check for WGMMA when `M < 64` or `block_size % 128 != 0`, simplifying the logic. (`src/op/gemm.cc`, [src/op/gemm.ccL226-L229](diffhunk://#diff-5cbeefe6d2ab80fbd4435060 …
=> [Enhancement] Remove DeReplicate during parallel loop layout inference

src/op/gemm.cc, src/tl_templates/cuda/gemm_sm80.h, src/tl_templates/cuda/gemm_sm89.h, src/tl_templates/cuda/gemm_sm90.h, testing/python/language/test_tilelang_language_cumsum.py
This pull request introduces significant updates to the GEMM (General Matrix Multiplication) implementation across multiple files, focusing on improving flexibility and correctness in operand handling and memory layout. The changes include additional template parameters for warp-level configurations, conditional logic for memory copy optimizations, and enhanced error checking for specific cases.
* Added a descriptive error message to the `ICHECK` condition in `Gemm::InferLayout` to clarify the requirement that `trans_B` must be `false` when `B` is a `local.fragment`.
* Introduced a new `num_warp_n` template parameter to `OperandTraits` in `gemm_sm80.h`, `gemm_sm89.h`, and `gemm_sm90.h`. This allows for more flexible configurations of warp-level memory layouts. …
=> [Enhancement] Support cute mma tile mxn8ky

src/op/reduce.cc, src/transform/pipeline_planning.cc, testing/python/language/test_tilelang_language_reduce_max.py, testing/python/language/test_tilelang_language_reduce_sum.py, testing/python/transform/test_tilelang_transform_annotate_device_regions.py, tilelang/language/reduce.py
This pull request introduces enhancements to the reduction operations in the TileLang framework, focusing on enabling accumulation without clearing output buffers, improving flexibility for specific use cases. It also adds comprehensive tests for the new functionality and updates the implementation of reduction operations to support this feature.
* **Support for Accumulation Without Clearing Buffers**:
- Added a `clear` parameter to `reduce_sum` and `reduce_absmax` functions in `tilelang/language/reduce.py`, allowing accumulation on existing buffer values when set to `False`. Updated the implementation to handle this behavior by using a temporary buffer during reduction. [[1]](diffhunk://#diff-d78b66b0ba55323f330d41a450cd5bc442704a6765d8aa698f98bdafe5dbc154L71-R92) …
=> [Language] Support accumulative `T.reduce_sum`

src/ir.cc
This pull request refactors the `KernelLaunch` function in `src/ir.cc` to improve clarity and consistency in handling CPU and GPU kernel launches. The most significant changes include reorganizing comments, ensuring proper annotations for blocks, and replacing empty block names with a more descriptive default.
* Reorganized the comment for launching the CPU kernel to align with the relevant code block, improving readability. [[1]](diffhunk://#diff-fd7749ba50b6074ced53829097c03ece00d7572477e24cf9dd416cd807dfe75fR165) [[2]](diffhunk://#diff-fd7749ba50b6074ced53829097c03ece00d7572477e24cf9dd416cd807dfe75fL173)
* Replaced empty block names (`Block("")`) with a more descriptive default (`Block("root")`) to enhance code clarity and maintain consistency. This change applies both when attributes …
=> [Refactor] Update KernelLaunch to clarify block name

src/op/parallel.cc
* Added logic to use non-replicated buffers as source buffers for more accurate layout inference.
* Enhanced comments to clarify the rationale behind buffer selection in layout inference process.
=> [Enhancement] Improve layout inference accuracy in ParallelOp

src/op/parallel.cc, src/tl_templates/cuda/common.h, src/tl_templates/hip/common.h, src/transform/loop_partition.cc, tilelang/__init__.py, tilelang/engine/phase.py, tilelang/jit/adapter/wrapper.py, tilelang/transform/__init__.py, tilelang/transform/pass_config.py
This pull request introduces several enhancements and bug fixes across multiple components of the TileLang compiler and runtime. The changes focus on improving error handling, adding configuration flexibility, optimizing performance, and enhancing code maintainability. Below is a categorized summary of the most important changes:
* Added `TILELANG_CHECK` macros in both `cuda/common.h` and `hip/common.h` to standardize error checking for CUDA and HIP API calls. These macros capture and log errors with detailed information, improving debugging capabilities. [[1]](diffhunk://#diff-a9affb584850fb57935aeb0a8450d96497f4534022304d408cb369a47d1e8130R30-R39) [[2]](diffhunk://#diff-688f4edb061910df1c04c5d483e0d7283b7bd5aadb4479bdff7f39fad1f6c0f9R29-R39)
* Enhanced kernel launch error handling in …
=> [Bugfix] Fix layout inference for free fragment buffer

requirements.txt
Previously, this was implemented to support float8. Now, the implementation has changed—float8-related calls are hidden and no longer explicitly invoked.
=> [Refactor] Phaseout torch>=2.2.0 dependency

src/tl_templates/cuda/common.h, src/tl_templates/hip/common.h, tilelang/jit/adapter/wrapper.py
This pull request introduces a macro to simplify and standardize error handling for CUDA and HIP kernel launches. The macro is then applied to replace repetitive error-handling code in the `tilelang/jit/adapter/wrapper.py` file. Below is a summary of the most important changes:
* [`src/tl_templates/cuda/common.h`](diffhunk://#diff-a9affb584850fb57935aeb0a8450d96497f4534022304d408cb369a47d1e8130R40-R49): Added the `TILELANG_CHECK_LAST_ERROR` macro to check for CUDA kernel launch errors, format error messages, and return `-1` if an error occurs.
* [`src/tl_templates/hip/common.h`](diffhunk://#diff-688f4edb061910df1c04c5d483e0d7283b7bd5aadb4479bdff7f39fad1f6c0f9R41-R50): Added the `TILELANG_CHECK_LAST_ERROR` macro for HIP kernel launches, mirroring the functionality of the CUDA macro but …
=> [Feature] Add TILELANG_CHECK_LAST_ERROR macro for improved error handling in CUDA and HIP

tilelang/__init__.py, tilelang/cache/__init__.py, tilelang/cache/kernel_cache.py
* Introduced `get_cache_dir` and `set_cache_dir` functions to manage the kernel cache directory.
* Updated `KernelCache` class to store cache directory as a `Path` object for improved path handling.
* Enhanced documentation with examples for new cache directory functions.
=> [Feature] Add cache directory management functions in tilelang.cache

tilelang/intrinsics/mma_layout.py
Current implementation of get_swizzle_layout only works for 16bit dtype and don't support 32B swizzle pattern.
This PR enable the swizzle pattern of 32B, 64B and 128B for all 8-128bit dtypes.
=> [Bugfix] Fix get_swizzle_layout implementation.

docs/get_started/Installation.md
When I built tile-lang from source, I found that compiling issues will raise if I use LLVM-20 due to the version of tvm submodule. Finally I fixed it by using lower version LLVM, therefore I'm adding a small hint to the doc in this PR.
Below is one of the errors:
```
/mnt/<user>/code/community/tilelang/3rdparty/tvm/src/target/llvm/codegen_amdgpu.cc:274:9: error: invalid use of incomplete type 'class llvm::Module'
274 |     mlib->setTargetTriple(llvm_target->GetTargetTriple());
```
=> docs: add llvm version info to installation.md.

src/transform/inject_tma_barrier.cc, tilelang/engine/phase.py
* Updated the TMA barrier validation in `inject_tma_barrier.cc` to check for non-empty `barrier_id_to_range_` before raising an error for missing `create_list_of_mbarrier`.
* Refactored architecture checks in `phase.py` to utilize a new constant `SUPPORTED_TMA_ARCHS`, allowing for easier updates and improved readability in the target architecture validation logic.
=> [Refactor] Enhance TMA barrier validation and support for additional architectures

src/op/math.cc, tilelang/language/tir/op.py
This pull request updates the naming convention for a mathematical operation in both C++ and Python code to ensure consistency and clarity. The changes primarily involve renaming the operation from `power_of_int` to `pow_of_int` across relevant files.
* In `src/op/math.cc`, the function `power_of_int_op` was renamed to `pow_of_int_op`, and associated strings and attributes were updated to reflect the new name. This includes changes to the operation name in `TVM_REGISTER_OP` and string literals used in the function.
* In `tilelang/language/tir/op.py`, the operation name passed to `tvm.tir.op.Op.get` was updated from `"tl.power_of_int"` to `"tl.pow_of_int"`.
=> [Typo] Rename `power_of_int` with `pow_of_int` for consistency

tilelang/autotuner/__init__.py, tilelang/jit/__init__.py
* Modified the `set_compile_args` method in `AutoTuner` to accept `None` as a valid input for the `out_idx` parameter, enhancing flexibility in argument handling.
=> [Refactor] Update set_compile_args to allow None for out_idx parameter

tilelang/language/copy.py
* Removed redundant logic for handling region extents in the buffer_region_to_tile_region function, streamlining the code for better readability and maintainability.
* Enhanced error handling by focusing on essential checks while eliminating unnecessary complexity related to variable extents.
=> [Refactor] Simplify buffer_region_to_tile_region function in copy.py

setup.py, src/transform/inject_tma_barrier.cc, tilelang/contrib/nvcc.py, tilelang/engine/phase.py
This pull request introduces logging enhancements to replace `print` statements with a standardized logging approach, improves GPU architecture handling, and refactors TMA (Tensor Memory Accelerator) support logic. These changes enhance maintainability, debugging, and extendability of the codebase.
* Added a logging configuration in `setup.py` for consistent logging across the script. Replaced all `print` statements with appropriate `logger` calls, such as `logger.info` and `logger.warning`. This includes updates in functions like `download_and_extract_llvm`, `is_git_repo`, `patch_libs`, and various methods in custom commands. [[1]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R24-R32) [[2]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aa …
=> [Refactor] Skip patchelf if not installed

src/layout/layout.cc, src/layout/layout.h, src/op/gemm.cc, src/op/parallel.cc, src/op/reduce.cc, src/transform/loop_partition.cc, tilelang/language/copy.py
This pull request introduces several fixes and enhancements across multiple files to improve layout inference, error messaging, and code clarity. The changes primarily focus on refining layout handling, ensuring consistent behavior, and simplifying logic.
* [`src/layout/layout.cc`](diffhunk://#diff-8e8b85e9396c3aaaf378020a15e4274510e97a4fb17c7c5ac7047596e1ca37c5L421-R425): Re-added a check for `ThreadRange` equality in the `IsEqual` method for `FragmentNode`, ensuring consistent structural comparisons.
* [`src/op/reduce.cc`](diffhunk://#diff-6db4f8a0f03dffeb4b8b493182b3754cc170d550bb6ea71ca472ced6320c8868L278-R279): Updated `ReduceOp::InferLayout` to set the thread range explicitly in the output layout using `SetThreadRange`, improving layout inference accuracy.
* …
=> [Refactor] Improve layout equality checks and error messaging

examples/deepseek_mla/example_mla_decode.py, tilelang/autotuner/__init__.py, tilelang/profiler/__init__.py
#PR: Fix Device Consistency in Autotuner Threads and Add Manual Profiler Check
This pull request addresses two important improvements to tilelang.autotuner:
1. **Bug Fix**: Ensures consistent CUDA device usage across threads in the autotuner
2. **New Feature**: Adds manual program check functionality to the profiler
When using ThreadPoolExecutor for parallel compilation in the autotuner, each worker thread might use a different CUDA device than the main thread. This inconsistency can lead to:
- Wrong Device of Input Tensor: the input tensors generated by `tilelang.utils.tensor.get_tensor_supply`  in each threads with be in `cuda:0`, instead of  `torch.cuda.current_device()` of the main process.
- Device resource conflicts
I've modified the autotuner to explicitly set the CUDA device in …
=> Fix Device Consistency in Autotuner Threads and Add Manual Profiler Check

tilelang/engine/phase.py
Due to #477, `have_tma(target)` calls will return error if target is not CUDA. Hence, this PR adds an additional check before calling `have_tma()`.
Another approach is to put CUDA target check inside `have_tma()` instead.
@LeiWang1999
=> [Bugfix] Check CUDA target before checking for TMA

src/layout/gemm_layouts.cc, src/layout/layout.h, src/op/gemm.cc, src/transform/layout_inference.cc, testing/python/kernel/test_tilelang_kernel_gemm.py
This pull request introduces support for transposed matrix multiplication in GEMM (General Matrix Multiplication) operations, refactors existing GEMM fragment generation, and adds new test cases to validate the changes. The key updates include adding support for transposed layouts in `makeGemmFragmentA` and `makeGemmFragmentB`, modifying GEMM layout inference to handle transposed matrices, and introducing new Python test functions for GEMM operations.
* **Support for Transposed Layouts in `makeGemmFragmentA` and `makeGemmFragmentB`:** Added a `bool transposed` parameter to these functions to generate fragments for transposed matrices. This includes logic for handling both transposed and non-transposed cases. (`src/layout/gemm_layouts.cc`: …
=> [Enhancement] Support register input for gemm when trans_a or trans_b is true

examples/dequantize_gemm/example_dequant_gemm.py, examples/dequantize_gemm/example_dequant_gemm_fine_grained.py, examples/dequantize_gemm/example_dequant_gemm_fp4_hopper.py, examples/dequantize_gemm/example_dequant_gemv_fp16xint4.py, examples/dequantize_gemm/test_example_dequantize_gemm.py, examples/flash_attention/example_mha_fwd_bhsd_wgmma_pipelined.py, tilelang/__init__.py, tilelang/quantize/__init__.py, tilelang/quantize/lop3.py, tilelang/quantize/quantization.py, tilelang/quantize/utils.py
This pull request introduces several changes across multiple files to enhance functionality, improve modularity, and add new features for dequantization and flash attention operations. The most significant updates include the addition of new examples for dequantization and flash attention, refactoring of existing scripts to improve usability, and updates to the `tilelang` library to support these operations.
* Added a new example in `examples/dequantize_gemm/example_dequant_gemv_fp16xint4.py` for dequantizing GEMV operations with support for various configurations, including fast decoding and scaling. This includes a comprehensive implementation of the `dequantize_gemv` function and a testable `main` function.
* Refactored `examples/dequantize_gemm/example_dequant_gemm_fp4_hopper.py` to …
=> [Refactor] Introduce quantize components of TileLang and add testing for dequant gemm exmaple

examples/blocksparse_attention/block_sparse_attn_triton.py, src/op/builtin.cc, src/op/builtin.h, src/transform/merge_shared_memory_allocations.cc, testing/python/kernel/test_tilelang_kernel_gemm.py, tilelang/autotuner/__init__.py, tilelang/engine/phase.py, tilelang/transform/__init__.py, tilelang/transform/pass_config.py
Add merge shared memory allocations pass and related configurations
- Introduced a new pass for merging shared memory allocations in GPU kernels, allowing for more efficient memory usage.
- Registered configuration options for debugging and controlling the merging behavior.
- Updated relevant files to integrate the new pass into the TileLang engine and transform modules.
- Adjusted import paths and added documentation for the new functionality.
=> [Enhancement] Introduce flag to visualize shared memory merge plan

src/layout/gemm_layouts.cc, src/op/gemm.cc
* Added detailed documentation for the makeGemmABLayout function, explaining parameters and layout selection strategies.
* Updated the layout selection logic to use mat_continuous consistently, enhancing clarity and correctness in memory layout calculations.
* Adjusted the InferLayout method to reflect changes in the layout function, ensuring accurate matrix dimension handling for transposed cases.
=> [Bugfix] Fix Hopper GEMM layout for small tile size

README.md, examples/deepseek_nsa/example_tilelang_nsa_bwd.py, examples/quickstart.py, examples/warp_specialize/example_warp_specialize_gemm_barrierpipe_stage2.py, examples/warp_specialize/example_warp_specialize_gemm_copy_0_gemm_1.py, examples/warp_specialize/example_warp_specialize_gemm_copy_1_gemm_0.py, examples/warp_specialize/example_warp_specialize_gemm_copy_gemm_0_1.py, examples/warp_specialize/example_warp_specialize_gemm_softpipe_stage2.py, testing/python/jit/test_tilelang_jit_gemm.py, testing/python/kernel/test_tilelang_kernel_gemm.py, testing/python/language/test_tilelang_language_alias.py, testing/python/language/test_tilelang_language_clear.py, testing/python/language/test_tilelang_language_copy.py, testing/python/language/test_tilelang_language_mask_op.py, tilelang/jit/__init__.py
* Renamed and refactored matmul and run_gemm functions to matmul_kernel_jit and run_gemm_kernel_jit for clarity.
* Removed redundant JIT decorator from the matmul function, ensuring it is applied only to the kernel function.
* Updated test function names to reflect changes in the kernel functions, enhancing consistency and readability.
* Cleaned up commented-out code and unnecessary imports to improve overall code quality.
=> [Refactor] Update JIT kernel functions and streamline GEMM tests

docker/Dockerfile.rocm, docker/README.md
The base image `rocm/pytorch:rocm6.3.2_ubuntu22.04_py3.10_pytorch_release_2.4.0` already includes conda.
The AMD-specific PyTorch environment is located in the `py_3.10` conda environment. This PR updates the Docker startup commands accordingly to activate the correct environment.
Tested successfully on MI300X hardware.
=> Fix AMD Docker issues related to conda environment setup

src/transform/layout_inference.cc, testing/python/jit/test_tilelang_jit_gemm.py, tilelang/jit/__init__.py, tilelang/jit/adapter/cython/cython_wrapper.pyx
* Refactored the `jit` class to `_JitImplementation` for clarity and encapsulation.
* Enhanced handling of `debug_root_path` to ensure it is correctly set as an absolute path when provided.
* Updated the public `jit` function to serve as a decorator interface, allowing for both default and configured usage.
* Added validation to ensure input tensors are contiguous in the Cython wrapper, improving error handling.
=>  [Refactor] Refactor `jit` to `_JitImplementation` to support `@tilelang.jit`

src/layout/gemm_layouts.cc
* Modified the layout creation in makeGemmFragmentB to enhance the order of operations, ensuring the Replicate method is called before Repeat for better readability and performance.
* This change improves the logical flow of fragment creation, aligning with best practices for GEMM layout management.
=> [Refactor] Adjust in fragment GEMM layout

src/transform/legalize_safe_memory_access.cc
* Refactored GlobalMemChecker to inherit from IRVisitorWithAnalyzer, enhancing its capabilities for expression analysis.
* Updated condition checks to utilize the new analyzer interface, improving clarity and correctness in memory access validation.
* Added additional lower bound condition checks to ensure comprehensive validation of memory access indices.
=> [Refactor] Update GlobalMemChecker to Detect Lower Bound illegal memory access automatically

src/layout/layout.cc, src/transform/lower_tile_op.cc
* Modified `makeBufferWithLayout` to include a `var_remap` parameter for improved variable remapping during buffer creation.
* Enhanced buffer load and store operations to utilize the new variable remapping logic, ensuring correct buffer references.
* Commented out a check in `ThreadExtent` for clarity, maintaining functionality while improving code readability.
=> [Refactor] Update buffer handling in layout transformation to support layout on `T.view` 

examples/quickstart.py, src/op/gemm.cc, src/tl_templates/cuda/gemm_sm80.h, src/tl_templates/cuda/gemm_sm89.h, src/tl_templates/cuda/gemm_sm90.h, tilelang/primitives/gemm/base.py
* Updated the warp partitioning logic in `Gemm::ComputeWarpPartition` to better handle various GEMM policies, including FullRow, FullCol, and Square.
* Implemented checks to dynamically adjust warp allocation based on matrix dimensions, ensuring optimal performance.
* Introduced a new `SelectCopy` template to streamline memory access patterns in CUDA templates, enhancing compatibility across different architectures.
* Refactored the Python `GemmWarpPolicy` class to align with the updated C++ logic, improving clarity and maintainability in warp allocation strategies.
=> [Bugfix] Enhance smem copy selector for uncommon shape

src/op/builtin.h, src/transform/layout_inference.cc, src/transform/legalize_safe_memory_access.cc, testing/python/language/test_tilelang_language_annotate_pad.py, tilelang/language/__init__.py
* Added a new attribute `kPaddingMap` in `builtin.h` for managing padding annotations.
* Enhanced `SafeMemorysRewriter` to utilize an annotated padding map for buffer stores, improving memory access safety.
* Implemented checks in `layout_inference.cc` to ensure buffers are correctly referenced during layout mapping.
* Introduced a new test file for validating the padding annotation functionality in TileLang.
=> [Enhancement] Introduce padding annotation and improve legalize safe memory access pass

src/transform/merge_shared_memory_allocations.cc, tilelang/engine/phase.py
* Introduced a new StmtAttr structure to track the scope level of statements, enhancing the liveness analysis process.
* Updated the UpdateStmtAttr function to manage statement attributes effectively during memory allocation visits.
* Modified the VisitStmt_ methods to utilize the new scope level tracking, ensuring accurate memory access patterns.
* Refactored the LivenessAnalysis and PlanMemory functions to incorporate statement attributes, improving the handling of gen and kill points in memory management.
* Added a new helper function allow_warp_specialized in phase.py to conditionally enable warp specialization based on pass context and target, addressing potential bugs in the MergeSharedMemoryAllocations pass.
* Enhanced the OptimizeForTarget function to conditionally apply the …
=> [Refactor] Enhance MergeSharedMemoryAllocations Pass for Improved Liveness Analysis and Scope Management

examples/grouped_gemm/example_grouped_gemm.py
* Introduced a new example script `example_grouped_gemm.py` demonstrating grouped matrix multiplication using TileLang and PyTorch.
* Implemented functions for performing grouped GEMM, constructing inputs, and validating results against PyTorch's implementation.
* Added command-line argument parsing for flexible input configuration, including batch sizes and matrix dimensions.
* Included a test function to validate the grouped GEMM functionality with various input scenarios.
=> [Dev] Add grouped GEMM example with TileLang and PyTorch integration

examples/deepseek_deepgemm/example_deepgemm_fp8_2xAcc.py
The origin example miss blockK, so have wrong logs: 
```
Traceback (most recent call last):
File "/A/tilelang/examples/deepseek_deepgemm/example_deepgemm_fp8_2xAcc.py", line 188, in <module>
assert_tl_gemm_correctness(1024, 1024, 8192, block_N, dtype, out_dtype, "float32")
TypeError: assert_tl_gemm_correctness() takes 6 positional arguments but 7 were given
```
Also add a line to print the running config, the result looks now: 
```
M=1024, N=1024, K=8192, block_N=16, in_dtype=e4m3_float8, out_dtype=bfloat16, accum_dtype=float32
diff: 3.2641305429681466e-06
latency: 0.17004799842834473 ms
tflops: 101.02952897289937
M=1024, N=1024, K=8192, block_N=32, in_dtype=e4m3_float8, out_dtype=bfloat16, accum_dtype=float32
diff: 3.2780839122059646e-06
latency: 0.1316480040550232 ms
tflops: …
```
=> Fix deepgemm exmaple 

src/tl_templates/cuda/common.h, tilelang/language/__init__.py, tilelang/language/customize.py
* Introduced `AtomicAddx2` and `AtomicAddx4` functions for performing atomic addition operations on double-width float types in CUDA.
* Updated `customize.py` to include the new `atomic_addx4` function for external calls.
* Modified `__init__.py` to export the new atomic addition function, ensuring accessibility in the module.
=> [Enhancement] Add atomicAdd for FLOAT16x2 and FLOAT16x4

src/op/gemm.cc, tilelang/jit/__init__.py
=> [Bugfix] Fix a bug when simplifying warp combination for T.gemm

src/tl_templates/cuda/gemm_sm80.h, src/tl_templates/cuda/gemm_sm89.h, src/tl_templates/cuda/gemm_sm90.h, src/transform/layout_inference.cc, tilelang/language/__init__.py
- Introduced a `cast_float_to_tf32` function to convert float32 values to tfloat32 format across gemm_sm80, gemm_sm89, and gemm_sm90 templates.
- Implemented conditional casting in relevant sections of the GEMM operations to ensure compatibility with tfloat32 types.
- Enhanced the handling of tensor views to support the new casting logic, improving performance and accuracy in matrix operations.
=> [Bugfix] Add tf32 casting to GEMM templates

examples/deepseek_mla/example_mla_decode_persistent.py, examples/gemm/example_gemm_persistent.py, src/ir.cc, src/op/builtin.cc, src/op/builtin.h, src/target/codegen_cuda.cc, src/target/codegen_cuda.h, src/transform/persist_threadblock.cc, src/transform/warp_specialized_rewriter.cc, tilelang/engine/phase.py, tilelang/jit/adapter/wrapper.py, tilelang/language/__init__.py, tilelang/language/builtin.py, tilelang/language/persistent.py, tilelang/transform/__init__.py
This pull request introduces several significant updates across multiple files to enhance functionality, optimize performance, and improve code maintainability. The changes include the addition of persistent threadblock support, new built-in operations, updates to CUDA code generation, and enhancements to existing primitives. Below is a categorized summary of the most important changes:
* Added a new transformation pass `PersistThreadblock` in `src/transform/persist_threadblock.cc` to enable threadblock persistence and synchronize threads across a grid. This includes detecting and substituting `sync_grid` calls.
* Integrated the `PersistThreadblock` transformation into the optimization pipeline in `tilelang/engine/phase.py`.
* Introduced two new built-in operations: `sync_grid` for grid …
=> [Feature] Introduce Persistent Loop and Update GEMM Example

src/layout/gemm_layouts.cc, src/layout/layout.h, src/op/bulk_copy.cc, src/op/gemm.cc, tilelang/autotuner/__init__.py
- Introduced a new `makeQuarterBankSwizzleLayout` function for layout swizzling of 32 bytes.
- Updated `makeGemmABLayout` to include an `enable_padding` parameter, allowing for conditional layout selection between padded and quarter bank swizzle layouts.
- Adjusted layout inference in GEMM operations to utilize the new quarter bank swizzle layout when appropriate.
- Enhanced bulk copy operations to recognize and handle the new layout type, improving memory access patterns.
TODO Items:
=> [Feature] Implement Swizzle 32B

.github/workflows/ci.yml, requirements-test.txt
- Replaced `flash-attn` with `packaging` and `wheel` in `requirements-test.txt` to ensure proper package management.
- Updated the CI workflow to install `flash-attn` without build isolation, improving the installation process.
=> [CI] Modify test requirements and CI workflow

examples/deepseek_nsa/example_tilelang_nsa_bwd.py, examples/deepseek_nsa/example_tilelang_nsa_fwd_varlen.py, examples/deepseek_nsa/example_triton_nsa_bwd.py, examples/deepseek_nsa/example_triton_nsa_fwd.py, examples/deepseek_nsa/example_triton_nsa_fwd_varlen.py
As mentioned in #574, since [FLA](https://github.com/fla-org/flash-linear-attention) update nsa's api in v0.2.1, we should use `from fla.ops.utils import prepare_token_indices` instead of `from fla.ops.common.utils import prepare_token_indices` when `fla.__version__ >= '0.2.1'` to fix the import issue.
=> [BugFix] Fix import error in nsa examples when `fla.__version__ >=0.2.1`

tilelang/jit/adapter/cython/cython_wrapper.pyx, tilelang/jit/adapter/utils.py, tilelang/utils/tensor.py
- Enhanced `pythonic_expr` to represent type casts as `(type)value` for better clarity in expression representation.
- Modified tensor validation in `CythonKernelWrapper` to conditionally check for tensor contiguity based on a new `skip_tensor_validation` parameter.
- Improved type mapping in `map_torch_type` to include version checks for new float8 types, ensuring compatibility with specific PyTorch versions.
=> [Enhancement] Update `pythonic_expr` to format type casts

tilelang/engine/param.py, tilelang/jit/adapter/cython/cython_wrapper.pyx
- Modified `KernelParam.from_var` to map Torch data types to a more appropriate format.
- Enhanced `CythonKernelWrapper` to support additional tensor types and ensure proper conversion of tensor dtypes to C types, improving error handling for unsupported types.
=> [Enhancement] Update dtype handling in cython adapters

tilelang/autotuner/__init__.py, tilelang/autotuner/param.py, tilelang/cache/tuner_cache.py, tilelang/jit/adapter/wrapper.py
- Enhanced the input tensor caching logic in the AutoTuner class to ensure compatibility between cached tensors and newly generated tensors during configuration trials.
- Added detailed logging to warn users about potential mismatches in tensor properties, including shape and dtype, when caching is enabled.
- Implemented a mechanism to regenerate input tensors if compatibility issues are detected, improving the robustness of the autotuning process.
- Eliminated redundant checks for existing cache paths in `AutotuneResult` and `AutoTunerCache` classes, simplifying the kernel saving
process.
- Ensured that the cache directory is always created before saving kernel source code, improving reliability in kernel storage.
=> [Bugfix] Fix input tensor compatibility checks in AutoTuner

src/transform/legalize_safe_memory_access.cc
- Updated the condition checks in the GlobalMemChecker to utilize symbolic bounds in the CanProve method, enhancing the accuracy of memory access validations.
- This change ensures that both upper and lower bound conditions are evaluated with improved proof strength, contributing to more robust memory access analysis.
=> [Enhancement] Improve memory access condition checks in GlobalMemChecker

src/op/builtin.cc, src/op/builtin.h, src/transform/merge_shared_memory_allocations.cc, tilelang/engine/phase.py, tilelang/transform/__init__.py, tilelang/transform/pass_config.py
=> [Enhancement] Introduce PassConfig `TL_ENABLE_AGGRESSIVE_SHARED_MEMORY_MERGE` to enable aggressive shared memory reuse

src/tl_templates/cuda/gemm_sm90.h
- Replaced the use of `tiled_mma.accumulate_ = GMMA::ScaleOut::Zero` with a call to `clear(acc)` for better clarity and maintainability in the accumulation logic.
- This change enhances the readability of the code by standardizing the approach to clearing accumulation values across multiple sections of the file.
=> [Bugfix] Update accumulation handling for mma fallback in gemm_sm90.h

src/layout/layout.cc, src/op/parallel.cc, src/transform/layout_inference.cc
- Updated the `DebugOutput` methods in `LayoutNode` and `FragmentNode` to provide more structured and informative output, including transformation details and thread range information.
- Enhanced layout inference logic in `ParallelOp` to add predicates for cross-thread shared memory access, improving layout handling in parallel operations.
- Minor adjustment in `layout_inference.cc` to ensure clarity in parallel loop handling.
=> [Bugfix] Avoid duplicate data access when cross thread buffer meet replicate register

examples/elementwise/example_elementwise_add.py, examples/quickstart.py, src/layout/gemm_layouts.cc
- Added a line break in `quickstart.py` for better readability.
- Simplified the JIT kernel compilation in `quickstart.py` by removing the unused execution backend option.
- Modified `example_elementwise_add.py` to disable cache for `tilelang` and optimized the element-wise addition kernel by utilizing shared memory for input tensors, improving performance.
- Updated default values for matrix dimensions and block sizes in the argument parser to enhance usability.
=> [Enhancement] Support tf32 gemm_rs

src/op/builtin.cc, src/op/builtin.h, tilelang/jit/adapter/ctypes/adapter.py, tilelang/jit/adapter/cython/adapter.py, tilelang/jit/adapter/libgen.py, tilelang/transform/pass_config.py
- Added `kDisableFastMath` and `kEnablePTXASVerboseOutput` configuration options to enhance control over compilation settings.
- Updated `LibraryGenerator` to utilize these new pass configurations, allowing for more flexible compilation behavior based on user preferences.
- Enhanced `PassConfigKey` enumeration to include the new options, ensuring they can be configured appropriately in the pass context.
=> [Enhancement] Introduce option `TL_DISABLE_FAST_MATH` and `TL_ENABLE_PTXAS_VERBOSE_OUTPUT`

src/op/reduce.cc
- Modified the `MakeInitValue` method in `ReduceOp` to handle integer data types correctly by returning appropriate minimum and maximum values based on the bit width.
- Added checks for integer types to ensure correct initialization for `kMax` and `kMin` reduction types, enhancing the robustness of the reduction operations.
=> [Enhancement] Update ReduceOp initialization values for integer types

pyproject.toml, setup.py
- Introduced a new `CythonExtension` class for building Cython-based extensions, enhancing the build process for Cython projects.
- Implemented functions to detect the Cython compiler and C++ compiler, improving compatibility and user experience.
- Updated the build process to handle Cython extensions alongside CMake extensions, ensuring a seamless integration for users.
- Added caching mechanisms for Cython compilation to optimize build times and reduce unnecessary recompilation.
=> [Enhancement] Add ahead of time cython compilation in setup.py

examples/dynamic_shape/example_dynamic.py, requirements-test.txt, tilelang/jit/adapter/utils.py, tilelang/jit/adapter/wrapper.py
- Added support for additional TIR expressions (FloorDiv, Min, Max, Add, Sub, FloorMod) in the pythonic_expr function to improve string representation.
- Replaced the deprecated legalize_c function calls in TLCUDASourceWrapper and TLCPUSourceWrapper with pythonic_expr for better expression handling in kernel launch code.
=> [Enhancement] Support more flexible layout host pythonic expr

examples/blocksparse_gemm/example_blocksparse_gemm.py, src/op/gemm.cc, src/op/parallel.cc, src/op/reduce.cc, src/tl_templates/cuda/reduce.h, src/transform/simplify.cc, tilelang/engine/phase.py, tilelang/transform/simplify.py
Simplify `(bx // 2 < seq_len)` to the compile-time constant `true` whenever `bx` is in the half-open interval `[0, seq_len * 2)`.
=> [Pass][Simplify] Introduce symbolic level simplify for condition expression

setup.py
- Included the Cython cache directory in the list of source files for the TileLang build process, ensuring proper handling of cached Cython files during the build.
=> [Enhancement] Automatically build and install cython into packages 

.github/workflows/ci.yml
=> [CI] Enable cache for virtual env and parallelize pytest via xdist

setup.py
cmake doesn't take the nvcc specified by CUDA_HOME by default. Consequently, the follow command failed for me because cmake still used the nvcc from the default location (e.g. in my case /usr/local/cuda/bin/nvcc):
```
$ PATH=/home/yangche/cuda-12.8/bin:$PATH CUDA_HOME=/home/yangche/cuda-12.8 pip install -e . -v
```
This minor fix enforces cmake to use the nvcc specified by the CUDA_HOME env.
=> [Bugfix] Passing correct nvcc to cmake

tilelang/autotuner/param.py, tilelang/autotuner/tuner.py, tilelang/cache/kernel_cache.py
This is a minor enhancement to output verbose messages indicating where cache files are saved and loaded. These messages are useful for examining the relevant intermediate files.
=> [Enhancement] Output cache-file-related messages with verbose=True

src/op/gemm.cc, src/op/gemm.h, src/target/utils.cc, src/target/utils.h
- Introduced a new `GetGemmInst` method to determine the appropriate GEMM instruction based on block size and target architecture.
- Updated `ComputeWarpPartition` to accept the GEMM instruction type, enhancing flexibility in warp partitioning logic.
- Added `TargetGetWarpSize` utility to streamline warp size retrieval based on target architecture.
- Refactored layout inference and lowering methods to utilize the new GEMM instruction handling, improving clarity and maintainability of the codebase.
=> [Refactor] Introduce GemmInst for different targets handling

examples/quickstart.py, tilelang/version.py
Although the local commit id cannot capture locally staged changes, the local commit id can help mitigate issues caused by incorrect cache to some extent, so it should still be kept.
=> [Version] Keep local commit id as it somehow help with debugging

examples/blocksparse_attention/example_tilelang_sparse_gqa_decode_paged.py, examples/blocksparse_attention/example_tilelang_sparse_gqa_decode_varlen_indice.py, examples/blocksparse_attention/example_tilelang_sparse_gqa_decode_varlen_mask.py, examples/blocksparse_attention/example_triton_sparse_gqa_decode_varlen_indice.py, examples/blocksparse_attention/example_triton_sparse_gqa_decode_varlen_mask.py, examples/flash_attention/bert_padding.py, examples/flash_attention/example_mha_fwd_varlen.py, requirements-test.txt
since we require only for correctness tests
as title, which maybe a stable version for `undefined symbol: _ZN3c104cuda9SetDeviceEi` as described in https://github.com/Dao-AILab/flash-attention/issues/966
=> [CI] Remove Flash Attention dependency

src/transform/inject_pipeline.cc, src/transform/pipeline_planning.cc, testing/python/transform/test_tilelang_transform_Inject_software_pipeline.py, tilelang/engine/phase.py
**Enhance Global Read Detection in Pipeline Planning**
- Improved the handling of global read detection by considering condition expressions within `IfThenElse` nodes, ensuring accurate identification of global memory accesses.  
- Added a dedicated flag to track whether the visitor is currently within a condition expression, enhancing the precision of buffer access analysis.  
- Refactored the `VisitStmt_` method to more cleanly process the structure of `IfThenElse` nodes, improving both readability and maintainability of the code.  
```cpp
// Skip condition expression of an IfThenElse node
// Example 1 (not a global read):
// shared[i] = T.if_then_else(global[i] < n, register_a[i], register_b[i])
//
// Example 2 (is a global read):
// shared[i] = T.if_then_else(global[i] < n, …
```
=> [Pipeline] Skip condition expression analysis for global reading
