tile-ai/tilelang

README.md

TileLang has been used in AttentionEngine

[Doc] update README that tilelang has been used in AttentionEngine

---

examples/flash_attention/example_mha_bwd.py
testing/python/kernel/test_tilelang_kernel_flash_linear_attention.py
testing/python/kernel/test_tilelang_kernel_mha.py
testing/python/transform/test_tilelang_transform_multi_version_buffer.py
testing/python/transform/test_tilelang_transform_warp_specialized.py
tilelang/language/builtin.py
tilelang/profiler/__init__.py

This PR adds the mha backward example in [example_mha_bwd.py](https://github.com/tile-ai/tilelang/compare/main...chengyupku:tilelang:main#diff-bd947c97342fb40b04c7abd0f1aec592a05c0c70bddd321ae46a35dd920a2eb4) for #75.

[Dev] Add mha backward example

---

examples/gemm_splitk/example_tilelang_gemm_splitk.py

This pull request includes a small change to the `examples/gemm_splitk/example_tilelang_gemm_splitk.py` file. The change involves removing the third parameter, `"shared"`, from the `T.alloc_shared` function calls to simplify the code.
- [`examples/gemm_splitk/example_tilelang_gemm_splitk.py`](diffhunk://#diff-ff374584f70360801b76e2cbf62639bec5262b9d61bef6c219f1a60a1367b550L21-R23): Removed the `"shared"` parameter from `T.alloc_shared` function calls.

[Typo] Fix a typo in gemm splitk examples

---

README.md

This pull request includes updates to the `README.md` file to add new example links and improve documentation.
Updates to documentation:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R29-R30): Added links to new examples for Flash MLA Decoding and Native Sparse Attention in the `examples` directory.

[Doc] Update README.md with new example links for Flash MLA Decoding and Native Sparse Attention

---

examples/linear_attention/example_retnet.py

This pull request introduces a new example for using the `tilelang` library with a RetNet model in the `examples/linear_attention/example_retnet.py` file.

[Dev] Add RetNet Linear Attention example

---

examples/deepseek_mla/README.md
examples/deepseek_mla/example_mla_decode.py

This pull request includes updates to the `examples/deepseek_mla` directory, specifically modifying the `README.md` file and the `example_mla_decode.py` script to improve clarity and consistency.

[Doc] Update MLA Documentation

---

install_cuda.sh

- Calculate 75% of available CPU cores for make jobs
- Prevent system unresponsiveness during build
- Dynamically adjust make job count based on system resources

[Enhancement] Optimize TileLang install scripts with Dynamic CPU Cores

---

examples/deepseek_mla/example_mla_decode.py

It's slightly faster than T.copy then RS-GEMM, and simpler.

Use SS-GEMM for PV in mla

---

src/ir.cc

- Introduce `CreateEnvThread` function to generate environment threads for GPU kernel launches
- Modify `KernelLaunch` to use `CreateEnvThread` for block and thread indices
- Improve thread variable naming with shorter, more descriptive identifiers (bx, by, bz, tx, ty, tz)
- Ensure proper thread environment setup within PrimFunc context

[Refactor] Enhance GPU Kernel Launch with Environment Thread Creation

---

src/runtime/runtime.cc
src/runtime/runtime.h
src/transform/lower_hopper_intrin.cc
tilelang/transform/__init__.py

[Bugfix] Make quickstart work properly on cu118

---

testing/python/language/test_tilelang_language_clamp.py
tilelang/language/__init__.py
tilelang/language/customize.py

Added the clamp function to T.language

[Language] Support clamp in language

---

examples/plot_layout/README.md

Expired example code, update readme.

Update expired example code.

---

examples/flash_attention/example_gqa_fwd_bshd_wgmma_pipelined.py

- Introduce `example_gqa_fwd_bshd_wgmma_pipelined.py` demonstrating a pipelined implementation of FlashAttention.
- Update sequence length parameter in existing example to 8192 and adjust number of stages for improved performance.
- Enhance argument parsing to accommodate new configurations for batch size, heads, and groups.

[Dev] Add new example for FlashAttention with pipelined execution

---

examples/flash_attention/example_gqa_bwd.py

- Introduce `example_gqa_bwd.py` demonstrating the backward pass of FlashAttention with pipelined execution.
- Implement forward and backward functions for FlashAttention, including preprocessing and postprocessing steps.
- Enhance argument parsing for batch size, heads, context size, and dimensions.
- Include a reference implementation for validation and performance benchmarking.

[Dev] Add GQA backward example

---

LICENSE

[LICENSE] Typo fix in LICENSE

---

examples/flash_attention/example_gqa_fwd_bshd.py

I have made some refinements to the `get_configs` function and implemented additional rules to minimize ineffective tuning attempts.

[Examples] Expand tuning configurations for FlashAttention example

---

testing/python/kernel/test_tilelang_kernel_int4_gemm_mma.py

Fix K // block_K to T.ceildiv(K,block_K) and add tests to testing/python/kernel/test_tilelang_kernel_int4_gemm_mma.py

[Fix] Fix K // block_K to T.ceildiv(K,block_K) and add tests

---

tilelang/jit/adapter/cython/adapter.py
tilelang/jit/adapter/cython/cython_wrapper.pyx

- Updated `CythonKernelAdapter` to support dynamic device assignment based on target type (CUDA, HIP, or CPU).
- Enhanced `CythonKernelWrapper` to include device management, ensuring tensors are allocated on the correct device.
- Added error handling for unsupported target types to improve robustness.

[Enhancement] Improve device handling in Cython kernel adapter

---

format.sh

- Modified `format.sh` to first check for the upstream repository before falling back to the local `origin/main` branch for determining the merge base.
- Improved logic to handle cases where the upstream repository is not available, ensuring robust file formatting across branches.

[Enhancement] Update format script to support force compare with upstream

---

examples/deepseek_mla/example_mla_decode.py
examples/deepseek_mla/example_mla_decode_paged.py
examples/flash_attention/example_gqa_fwd_bshd.py
examples/flash_attention/example_gqa_fwd_bshd_wgmma_pipelined.py
examples/flash_attention/example_mha_fwd_bhsd.py
examples/flash_attention/example_mha_fwd_bshd.py
examples/flash_attention/example_mha_fwd_bshd_wgmma_pipelined.py

- Replaced instances of `tilelang.lower` and `tilelang.Profiler` with `tilelang.compile` and the new profiler interface in multiple example files.
- Enhanced the kernel compilation process to utilize the updated API, improving consistency and maintainability.
- Adjusted benchmarking logic to use the new profiler methods for better clarity and functionality in performance testing.
- Cleaned up whitespace and improved formatting for better readability across the modified files.

[Refactor] Update kernel compilation and profiling in examples

---

README.md

This pull request includes an update to the `README.md` file to add a citation section for the TileLang repository.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R230-R241): Added a new "Citation" section with a BibTeX entry for citing the TileLang repository.

[Readme] Update Bib Citation Section

---

examples/cumsum/example_tilelang_cumsum.py
examples/flash_attention/example_mha_bwd.py
src/transform/legalize_safe_memory_access.cc
tilelang/cache/kernel_cache.py
tilelang/language/__init__.py
tilelang/language/kernel.py

This pull request introduces several changes across multiple files to improve GPU kernel generation, caching, and memory access handling. The most important changes include the addition of a new GPU kernel for 2D continuous cumulative sum, refactoring to replace cached functions with direct kernel compilation, and updates to the `SafeMemorysRewriter` class to handle specific conditions.
* [`examples/cumsum/example_tilelang_cumsum.py`](diffhunk://#diff-54664395eb9d7b5b8fe3bde955a1788a5a2dd82017e9ba2c86af6004ffe38fd0R1-R200): Added a new function `gpu_2d_continuous_cumsum` to generate a GPU kernel for 2D continuous cumulative sum, including detailed parameter documentation and implementation.
* [`examples/flash_attention/example_mha_bwd.py`](diffhunk://#diff-bd947c97342fb40b04c7abd0f1aec592a …

[Example] Implement Kernel Example cumsum

---

tilelang/cache/kernel_cache.py

otherwise it will make multi-thread autotune have sequential compilation

[Refactor] Move compilation outside critical section

---

benchmark/matmul/benchmark_matmul.py
benchmark/matmul/benchmark_matmul_intrinsic.py
examples/convolution/example_convolution.py
examples/dequantize_gemm/example_dequant_gemm_fp4_hopper.py
examples/flash_attention/example_gqa_fwd_bshd.py
examples/flash_attention/example_gqa_fwd_bshd_wgmma_pipelined.py
examples/flash_attention/example_mha_fwd_bhsd.py
examples/flash_attention/example_mha_fwd_bshd.py
examples/flash_attention/example_mha_fwd_bshd_wgmma_pipelined.py
examples/flash_decoding/example_gqa_decode.py
examples/gemm/example_gemm.py
examples/linear_attention/example_mamba_chunk_scan.py
examples/linear_attention/example_mamba_chunk_state.py
install_cuda.sh
tilelang/autotuner/__init__.py
tilelang/jit/adapter/base.py
tilelang/jit/kernel.py

This PR fixes bugs after https://github.com/tile-ai/tilelang/pull/252 is merged.

[Bugfix] Fix Benchmark/Example Code for Autotuning

---

testing/python/language/test_tilelang_language_alias.py
tilelang/__init__.py
tilelang/cache/kernel_cache.py
tilelang/env.py
tilelang/language/__init__.py
tilelang/language/copy.py
tilelang/language/frame.py
tilelang/language/gemm.py

This pull request includes several changes to enhance the functionality and maintainability of the `tilelang` package. The most important changes include adding a new test file for matrix multiplication, implementing cache control functions, and introducing a new `LetFrame` class to handle variable values in a stack.
* [`testing/python/language/test_tilelang_language_alias.py`](diffhunk://#diff-509ec67d6d492fb29d33f99d53d73dde46ae5481eda8320de645707e637d6e21R1-R55): Added a new test file for matrix multiplication, including the `matmul` function, `run_matmul` function, and `test_matmul` function.
* [`tilelang/env.py`](diffhunk://#diff-ddadb040db7dc051ec0ad90b877e6d7784581e57d1137a25a4354be788aab82fR125-R155): Implemented cache control functions `enable_cache`, `disable_cache`, and …

[Language] Enhance alias to support blockwise memory load

---

src/transform/warp_specialized_rewriter.cc

- Introduced TMAFinder and ProducerUsedBufferFinder classes to analyze TMA loads and identify buffers used in producer conditions.
- Enhanced WarpSpecializedRoleMarker to prepare and utilize the identified buffers during role marking.
- Updated VisitStmt methods to incorporate new analysis logic for IfThenElse and For nodes, improving the handling of TMA loads in the warp specialization process.

[Bugfix] Add TMA and Producer Buffer Analysis in Warp Specialized Rewriter

---

src/tl_templates/cuda/common.h
tilelang/autotuner/__init__.py
tilelang/cache/kernel_cache.py
tilelang/language/allocate.py
tilelang/language/builtin.py
tilelang/language/copy.py
tilelang/language/customize.py
tilelang/language/frame.py
tilelang/language/gemm.py
tilelang/language/memscope.py
tilelang/language/reduce.py

This pull request includes changes to multiple files to improve documentation and add new functionality. The most important changes include adding comprehensive docstrings to several classes and methods, modifying the `KernelCache` class to enhance thread safety, and adding conditional compilation for BFLOAT16 atomic operations.
* [`tilelang/autotuner/__init__.py`](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7dd38L3-R7): Added detailed docstrings to the `JITContext`, `AutotuneResult`, and `AutoTuner` classes, as well as their methods, to provide better context and usage information. [[1]](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7dd38L3-R7) [[2]](diffhunk://#diff-97693b0284b022034f1372b32098a5c8665f29f882a79e3739f19a340ea7d …

[Refactor] Improve documentation and add detailed docstrings across multiple modules

---

examples/deepseek_deepgemm/example_deepgemm_fp8_2xAcc.py

block_N can be 2^n to support more flexible block tuning.

Support block_N sizes that are 2^n in deepgemm example

---

examples/flash_decoding/example_sparse_gqa_decode_varlen.py
examples/flash_decoding/heuristic.py
src/transform/loop_vectorize_dynamic.cc

[Dynamic Symbolic] Adaptively vectorize with different condition expressions

[Dynamic Symbolic] Adaptively vectorize with different condition expressions

---

examples/flash_decoding/example_gqa_decode.py

- Added a manual seed for reproducibility in PyTorch.
- Refactored local variable allocations for better memory management.
- Enhanced parallel processing in the flashattn function to improve performance.
- Updated layout annotations for clarity and efficiency.
These changes optimize the flash attention mechanism and ensure consistent behavior across runs.

[Bugfix] Fix fragment layout annotation in example gqa decode

---

examples/cast/example_group_per_split_token_cast_to_fp8.py

- Modified the `group_per_split_token_cast_to_fp8` function to include a conditional check for batch sizes, ensuring that the scaling factor is applied only when within the valid range. This change enhances the robustness of the FP8 conversion process for grouped per-split tokens.

 [Bugfix] Fix X_amax Correctness Issue in Group Cast FP8

---

examples/cast/example_group_per_split_token_cast_to_fp8.py

- Modified the `group_per_split_token_cast_to_fp8` function to support `bfloat16`, `float`, and `float16` data types.
- Updated local fragment allocations to use the new `accum_dtype` for consistency.
- Enhanced the main execution block to handle different tensor data types based on the specified `dtype`, improving flexibility in tensor operations.

[Enhancement] Update group_per_split_token_cast_to_fp8 to support multiple data types

---

examples/gemm/example_gemm.py
examples/gemm/example_gemm_autotune.py

* Added a new example script `example_gemm_autotune.py` to demonstrate autotuning for matrix multiplication (GEMM) using TileLang.
* Implemented functions for generating configurations, selecting the best configuration, and benchmarking performance.
* Refactored the existing `matmul` function to support dynamic configuration parameters and improved kernel compilation.
* Updated the main execution block to include command-line argument parsing for matrix dimensions and autotuning options.
* Enhanced the example to validate results against a reference implementation, ensuring correctness in matrix multiplication operations.

[Example] Introduce autotuning example for GEMM with enhanced configuration options

---

tilelang/engine/phase.py
tilelang/jit/adapter/cython/adapter.py

This pull request includes updates to the `tilelang/jit/adapter/cython/adapter.py` file to improve code readability by translating comments from Chinese to English. 
Changes to improve code readability:
* [`tilelang/jit/adapter/cython/adapter.py`](diffhunk://#diff-fb6f070e77115039cffa90aea9d733c451c961c1c517ad15f5f58487a4ab1548L75-R75): Updated comment to "remove the incomplete file" in the `get_cached_lib` function.
* [`tilelang/jit/adapter/cython/adapter.py`](diffhunk://#diff-fb6f070e77115039cffa90aea9d733c451c961c1c517ad15f5f58487a4ab1548L116-R116): Updated comment to "compile the cython_wrapper.pyx file into .cpp" in the `get_cached_lib` function.
* [`tilelang/jit/adapter/cython/adapter.py`](diffhunk://#diff-fb6f070e77115039cffa90aea9d733c451c961c1c517ad15f5f58487a4ab1548L126-R126): …

[Typo] Remove unused comments generated by copilot

---

docs/index.md
examples/flash_decoding/example_gqa_decode.py
setup.py
tilelang/jit/adapter/cython/adapter.py

This pull request includes changes to the documentation for deep learning operators. The most important change is the addition of a new operator to the list of documented operators.
Documentation updates:
* [`docs/index.md`](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R43): Added `deeplearning_operators/deepseek_mla` to the list of deep learning operators.

[Doc] Add deepseek_mla to documentation index

---

.gitignore
examples/dynamic/example_dynamic.py
src/op/builtin.cc
src/op/builtin.h
src/transform/loop_vectorize_dynamic.cc
src/transform/make_packed_api.cc
testing/python/dynamic/test_tilelang_dynamic_symbolic.py
testing/python/dynamic/test_tilelang_dynamic_symbolic_bench.py
tilelang/jit/__init__.py
tilelang/jit/kernel.py

Add pass_config to customize vectorization and tail split

[Dynamic Symbolic] Add pass_config to customize vectorization and tail split

---

README.md
examples/deepseek_mla/amd/README.md

This pull request includes updates to the `README.md` and `examples/deepseek_mla/amd/README.md` files to reflect new performance achievements and acknowledge contributions from the AMD ROCm and Composable Kernel team. The most important changes include adding a new high-performance FlashMLA implementation for AMD MI300X, updating performance analysis results, and adding an acknowledgment section.
Updates to documentation:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R14): Added a new entry for the high-performance FlashMLA implementation for AMD MI300X, achieving performance parity with hand-optimized assembly kernels.
* [`examples/deepseek_mla/amd/README.md`](diffhunk://#diff-56b3dd86baa8dd4fb1aeb6e5d163ad01fe302a078db4d0be213fe7158fe381 …

[Doc] Update README.md for deepseek_mla on AMD

---

docs/get_started/Installation.md

Set USE_LLVM to optional in ''docs/get_started/Installation.md''.

[Refactor] set USE_LLVM to optional.

---

tilelang/autotuner/__init__.py

Revert "[Bugfix] Use AutoTune cache_input_tensors properly"

---

src/op/reduce.cc
tilelang/jit/kernel.py
tilelang/language/reduce.py

* Updated ReduceOp to handle 1D reduction cases and ensure correct dimension checks, improving robustness in reduction operations.
* Initialized prim_func in JITKernel to enhance clarity and prevent potential null reference issues.
* Added whitespace for better code readability in reduce.py.

[Enhancement] Enhance ReduceOp and JITKernel for improved dimension handling and initialization

---

examples/fusedmoe/example_fusedmoe_tilelang.py
examples/fusedmoe/example_fusedmoe_torch.py
examples/fusedmoe/test_example_fusedmoe.py

- Add FusedMoE example based on our implementation in AMD scenario

[CI] Add FusedMoE example

---

examples/flash_attention/example_gqa_bwd.py
examples/flash_attention/example_gqa_fwd_bshd.py
examples/flash_attention/example_gqa_fwd_bshd_wgmma_pipelined.py
examples/flash_attention/example_mha_bwd.py
examples/flash_attention/example_mha_bwd_wgmma_pipelined.py
examples/flash_attention/example_mha_fwd_bhsd.py
examples/flash_attention/example_mha_fwd_bhsd_wgmma_pipelined.py
examples/flash_attention/example_mha_fwd_bshd.py
examples/flash_attention/example_mha_fwd_bshd_wgmma_pipelined.py
examples/flash_attention/example_mha_fwd_varlen.py
examples/flash_attention/example_mha_inference.py
examples/flash_attention/test_example_flash_attention.py
tilelang/engine/phase.py

Added a CI test file test_example_flash_attention.py for the files under tilelang/examples/flash_attention.

[CI] Add CI test for flash_attention examples

---

README.md

[Doc] `README.md` deepseek_nsa Link correction

---

tilelang/autotuner/__init__.py

- Simplified the shape comparison logic in the AutoTuner class to enhance readability and maintainability.
- Ensured that the shape compatibility checks are more concise while preserving functionality, contributing to overall code clarity.

[Refactor] Improve tensor shape compatibility checks in AutoTuner

---

tilelang/autotuner/__init__.py
tilelang/env.py

- Introduced environment variables for CPU utilization, counts, and maximum CPU count for auto-tuning.
- Updated the AutoTuner class to utilize these new settings, improving flexibility and performance in multi-threaded environments.
- Enhanced logging to provide better insights into the auto-tuning process based on the configured CPU settings.

[Enhancement] Add CPU utilization and count settings for Auto-Tuning

---

examples/deepseek_mla/benchmark_mla.py
examples/deepseek_mla/example_mla_decode_paged.py

- Enhanced the condition in `compare_ab` to ensure baseline checks align with target exclusions.
- Removed unnecessary tensor allocation in `mla_decode_tilelang`, optimizing memory usage and improving performance by directly using shared tensors in GEMM operations.

[Dev] Update benchmark and decoding scripts to refine condition checks and optimize tensor operations

---

tilelang/jit/adapter/cython/cython_wrapper.pyx

[Enhancement] Support torch.bool as kernel input

---

src/op/reduce.cc

as title, otherwise may lead to unknown issues.

[Bugfix] Put thread_extent into reduce

---

examples/blocksparse_attention/README.md
examples/blocksparse_attention/example_tilelang_sparse_gqa_decode_paged.py

Add a paged block-sparse flash-decoding kernel similar to mla paged implementation.

[Example] Add paged block-sparse flash-decoding kernel

---

tilelang/engine/phase.py

- Added a comment to clarify the alignment of dynamic shared memory allocations in the `OptimizeForTarget` function.
- Refactored the handling of shared memory allocation merging and synchronization to streamline the process, ensuring consistent behavior regardless of the aggressive merge flag.
- Improved code clarity by removing redundant conditional checks related to synchronization and memory allocation.

[Enhancement] Align dynamic shared memory allocations in phase.py

---

src/tl_templates/cuda/reduce.h

- Modified the AllReduce struct to include thread offset parameters in the run and run_hopper methods, improving thread management during reduction operations.
- Adjusted memory buffer indexing to account for thread offsets, enhancing performance and accuracy in GPU architectures.
- This change streamlines the handling of thread offsets, ensuring consistent behavior across different configurations.

[Bugfix] Added missing thread offsets and other information to reduce

---

.clang-tidy

Do not check for short variables

---

examples/grouped_gemm/example_grouped_gemm_fwd.py
src/transform/warp_specialized_rewriter.cc

- Removed unnecessary configurations from the @tilelang.jit decorator in `example_grouped_gemm_fwd.py`, simplifying the kernel compilation process.
- Updated the `grouped_gemm` function to accept a tuple for batch sizes, enhancing compatibility with the kernel invocation.
- Added logic in `warp_specialized_rewriter.cc` to track buffer usage in `CallNode` expressions, improving the handling of TMA load operations.
This refactor aims to streamline the code and improve maintainability while ensuring better performance in grouped matrix multiplication operations.

[Enhancement] Enhance warp specialization logic

---

.github/workflows/ci.yml

[CI] Bind build-test CI to NVIDIA as AMD runners are being introduced

---

src/target/codegen_cuda.cc
src/tl_templates/cuda/copy_sm90.h

[Refactor] Refactor CUDA code generation to simplify eviction policy handling
